applications:
  - name: Messaging
    enabled: true
    unify:
      listed: true
      icon: /applications/messaging.png
      logo: /applications/messaging.png
      url: /messaging

  - name: Low Code
    enabled: true
    unify:
      listed: true
      icon: /applications/low-code-platform.png
      logo: /applications/low-code-platform.png
      url: /admin


  - name: Corteza Admin Area
    enabled: true
    unify:
      listed: true
      icon: /applications/admin-area.png
      logo: /applications/admin-area.jpg
      url: /admin

  - name: Corteza Jitsi Bridge
    enabled: true
    unify:
      listed: true
      icon: /applications/video-conference.png
      logo: /applications/video-conference.png
      url: /bridge/jitsi/

  - name: Google Maps
    enabled: true
    unify:
      listed: true
      icon: /applications/google-maps.png
      logo: /applications/google-maps.png
      url: /bridge/google-maps/

  - name: CRM
    enabled: true
    unify:
      listed: true
      icon: /applications/low-code-crm-app.png
      logo: /applications/low-code-crm-app.png
      url: /compose/ns/crm/pages

  - name: Service Solution
    enabled: true
    unify:
      listed: true
      icon: /applications/low-code-service-solution-app.png
      logo: /applications/low-code-service-solution-app.png
      url: /compose/ns/service-solution/pages
