settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: false
schema:

# ######################################################################################################################
- name: sys
  path: cmd/system
  commands:
    vet:
      status: false
    test:
      status: false
    run:
      status: true
  args:
    - serve-api
  watcher:
    paths:
      - .
      - ../../system
      - ../../pkg
      - ../../internal
    extensions:
      - go
    ignored_paths:
      - ../../vendor
      - ../../.git

# ######################################################################################################################
- name: msg
  path: cmd/messaging
  commands:
    vet:
      status: false
    test:
      status: false
    run:
      status: true
  args:
    - serve-api
  watcher:
    paths:
      - .
      - ../../messaging
      - ../../pkg
      - ../../internal
    extensions:
      - go
    ignored_paths:
      - ../../vendor
      - ../../.git

# ######################################################################################################################
- name: cmp
  path: cmd/compose
  commands:
    vet:
      status: false
    test:
      status: false
    run:
      status: true
  args:
    - serve-api
  watcher:
    paths:
      - .
      - ../../compose
      - ../../pkg
      - ../../internal
    extensions:
      - go
    ignored_paths:
      - ../../vendor
      - ../../.git
