settings:
  flimit: 1000

schema:
# ######################################################################################################################
- name: "COR"
  path: "./cmd/monolith"
  commands: { run: { status: true } }
  args: [ "serve-api" ]
  watcher:
    paths: [ "." , "../../system" , "../../messaging" , "../../compose" , "../../pkg" , "../../internal" ]
    extensions: [ "go" ]
    ignored_paths: [ "../../vendor", "../../.git" ]
