settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: false
schema:
- name: sam
  path: cmd/sam
  commands:
    vet:
      status: true
    test:
      status: false
    run:
      status: true
  args:
  - api
  watcher:
    paths:
    - .
    - ../../sam
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
- name: crm
  path: cmd/crm
  commands:
    vet:
      status: true
    test:
      status: false
    run:
      status: true
  args:
  - api
  watcher:
    paths:
    - .
    - ../../crm
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
