FROM golang:1.12-alpine

RUN	apk add --no-cache git make bash && \
	echo "installing gomock" && go get -u github.com/golang/mock/gomock && \
	echo "installing mockgen" && go get -u github.com/golang/mock/mockgen && \
	echo "installing gotest" && go get -u github.com/rakyll/gotest && \
	echo "installing goware/statik" && go get -u github.com/goware/statik && \
	cd /usr/local/bin && wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod a+x wait-for-it.sh