## builder image
FROM cortezaproject/corteza-server-builder:latest AS builder

WORKDIR /go/src/github.com/cortezaproject/corteza-server

COPY . .

RUN scripts/builder-make-bin.sh messaging /tmp/corteza-server-messaging

## == target image ==

FROM alpine:3.7

RUN apk add --no-cache ca-certificates

COPY --from=builder /tmp/corteza-server-messaging /bin

EXPOSE 80
ENTRYPOINT ["/bin/corteza-server-messaging"]

# Forcing exposed port
CMD ["serve-api", "--messaging-http-addr=:80"]

