version: "3"
services:
  pg:
    image: postgres:12.4
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  db:
    image: percona:8.0
    restart: on-failure
    environment:
      # To be picked up by percona image when creating the database
      # Must match with DB_DSN settings inside .env
      MYSQL_DATABASE:      corteza
      MYSQL_USER:          corteza
      MYSQL_PASSWORD:      rootcorteza
      MYSQL_ROOT_PASSWORD: rootcorteza
    volumes: [ "./data/db:/var/lib/mysql" ] # use local fs
    ports:
      - 3306:3306
