## builder image
FROM cortezaproject/corteza-server-builder:latest AS builder

WORKDIR /corteza/src

COPY . .

RUN scripts/builder-make-bin.sh messaging /tmp/corteza-server-messaging

## == target image ==

FROM alpine:3.7

RUN apk add --no-cache ca-certificates

COPY --from=builder /tmp/corteza-server-messaging /bin

ENV STORAGE_PATH /data
ENV CORREDOR_ADDR corredor:80

VOLUME /data

EXPOSE 80
ENTRYPOINT ["/bin/corteza-server-messaging"]

CMD ["serve-api"]

