## builder image
FROM cortezaproject/corteza-server-builder:latest AS builder

WORKDIR /corteza/src

COPY . .

RUN scripts/builder-make-bin.sh system /tmp/corteza-server-system

## == target image ==

FROM alpine:3.7

RUN apk add --no-cache ca-certificates

COPY --from=builder /tmp/corteza-server-system /bin

ENV STORAGE_PATH /data
ENV CORREDOR_ADDR corredor:80

VOLUME /data


EXPOSE 80
ENTRYPOINT ["/bin/corteza-server-system"]

CMD ["serve-api"]

