## builder image
FROM cortezaproject/corteza-server-builder:latest AS builder

WORKDIR /go/src/github.com/cortezaproject/corteza-server

COPY . .

RUN scripts/builder-make-bin.sh monolith /tmp/corteza-server

## == target image ==

FROM alpine:3.7

RUN apk add --no-cache ca-certificates

COPY --from=builder /tmp/corteza-server /bin

EXPOSE 80
ENTRYPOINT ["/bin/corteza-server"]

# Forcing exposed port
CMD ["serve-api"]
