## builder image
FROM cortezaproject/corteza-server-builder:latest AS builder

WORKDIR /go/src/github.com/cortezaproject/corteza-server

COPY . .

RUN scripts/builder-make-bin.sh system /tmp/corteza-server-system

## == target image ==

FROM alpine:3.7

RUN apk add --no-cache ca-certificates

COPY --from=builder /tmp/corteza-server-system /bin

ENV SYSTEM_STORAGE_PATH /data/system

VOLUME /data


EXPOSE 80
ENTRYPOINT ["/bin/corteza-server-system"]

CMD ["serve-api"]

