[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/titpetric/factory"

[[constraint]]
  branch = "v2"
  name = "github.com/crusttech/go-oidc"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.1"
