import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faGripHorizontal,
  faGripLines,
  faThumbtack,
  faBars,
  faChevronUp,
  faChevronDown,
  faSearch,
  faMapMarkedAlt,
  faTimes,
  faLocationArrow,
  faCheckDouble,
  faBellSlash,
  faBell as faBellSolid,
  faEllipsisV,
  faCheck,
  faLocationCrosshairs,
} from '@fortawesome/free-solid-svg-icons'
import {
  faQuestionCircle,
  faUser,
  faBell,
  faTrashAlt,
  faEnvelope,
  faEnvelopeOpen,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  faUser,
  faQuestionCircle,
  faGripHorizontal,
  faThumbtack,
  faBars,
  faChevronDown,
  faChevronUp,
  faSearch,
  faMapMarkedAlt,
  faTimes,
  faLocationArrow,
  faCheckDouble,
  faBell,
  faBellSolid,
  faBellSlash,
  faEllipsisV,
  faTrashAlt,
  faGripLines,
  faCheck,
  faLocationCrosshairs,
  faEnvelope,
  faEnvelopeOpen,
)
