/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddableEdge: typeof import('./src/components/flow/AddableEdge.vue')['default']
    BranchNode: typeof import('./src/components/flow/BranchNode.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConfigSidebar: typeof import('./src/components/builder/ConfigSidebar.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    DynamicForm: typeof import('./src/components/builder/form/DynamicForm.vue')['default']
    DynamicInput: typeof import('./src/components/builder/form/DynamicInput.vue')['default']
    EndNode: typeof import('./src/components/flow/EndNode.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    NodePicker: typeof import('./src/components/builder/NodePicker.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepNode: typeof import('./src/components/flow/StepNode.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TriggerNode: typeof import('./src/components/flow/TriggerNode.vue')['default']
  }
}
