applications:
  - name: Namespaces
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/low-code-platform.png
      logo: applications/low-code-platform.png
      url: compose/

  - name: Admin Area
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/admin-area.png
      logo: applications/admin-area.png
      url: admin/

  - name: Workflows
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/workflows.png
      logo: applications/workflows.png
      url: workflow/

  - name: Jitsi Video Conferencing
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/video-conference.png
      logo: applications/video-conference.png
      url: bridge/jitsi/

  - name: Reporter
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/reporter.png
      logo: applications/reporter.png
      url: reporter/

  - name: Privacy
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/privacy.png
      logo: applications/privacy.png
      url: privacy/
