applications:
  - name: Namespaces
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/low-code-platform.png
      logo: applications/low-code-platform.png
      url: compose/

  - name: Admin Area
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/admin-area.png
      logo: applications/admin-area.png
      url: admin/

  - name: Workflows
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/workflows.png
      logo: applications/workflows.png
      url: workflow/

  - name: Automation
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      url: taq/

  - name: Agentic
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      url: agentic/

  - name: One
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      url: one/

  - name: Two
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      url: /
