import:
  - github.com/cortezaproject/corteza-server/system/types

interface:
  - system/service
  - provision/system

fields:
  - { field: ID }
  - { field: Name }
  - { field: OwnerID }
  - { field: Enabled }
  - { field: Unify }
  - { field: CreatedAt }
  - { field: UpdatedAt }
  - { field: DeletedAt }

lookups:
  - fields: [ ID ]
    description: |-
      searches for application by ID

      It returns application even if deleted

rdbms:
  alias: app
  table: applications
  customFilterConverter: true
