import:
  - github.com/cortezaproject/corteza-server/system/types

fields:
  - { field: ID }
  - { field: Name,      sortable: true }
  - { field: OwnerID }
  - { field: Enabled }
  - { field: Weight,    sortable: true }
  - { field: Unify }
  - { field: CreatedAt, sortable: true }
  - { field: UpdatedAt, sortable: true }
  - { field: DeletedAt, sortable: true }

lookups:
  - fields: [ ID ]
    description: |-
      searches for application by ID

      It returns application even if deleted

functions:
  - name: ApplicationMetrics
    return: [ "*types.ApplicationMetrics", "error" ]

  - name: ReorderApplications
    arguments:
      - { name: order, type: "[]uint64" }
    return: [ "error" ]


rdbms:
  alias: app
  table: applications
  customFilterConverter: true
