import:
  - github.com/cortezaproject/corteza-server/compose/types

types:
  type: types.Chart

fields:
  - { field: ID }
  - { field: Handle, lookupFilterPreprocessor: lower, sortable: true, unique: true }
  - { field: Name,                                    sortable: true }
  - { field: Config, type: "types.ChartConfig" }
  - { field: NamespaceID }
  - { field: CreatedAt,                               sortable: true }
  - { field: UpdatedAt,                               sortable: true }
  - { field: DeletedAt,                               sortable: true }

lookups:
  - fields: [ ID ]
    description: |-
      searches for compose chart by ID

      It returns compose chart even if deleted
  - fields: [ NamespaceID, Handle ]
    filter: { DeletedAt: nil }
    description: |-
      searches for compose chart by handle (case-insensitive)

rdbms:
  alias: cch
  table: compose_chart
  customFilterConverter: true
