import:
  - github.com/cortezaproject/corteza-server/compose/types

interface:
  - compose/service

types:
  type: types.Page

fields:
  - { field: ID }
  - { field: SelfID, column: "self_id" }
  - { field: NamespaceID }
  - { field: ModuleID }
  - { field: Handle, lookupFilterPreprocessor: lower }
  - { field: Title }
  - { field: Description, type: "string" }
  - { field: Blocks, type: "types.PageBlocks" }
  - { field: Visible, type: bool }
  - { field: Weight, type: int  }
  - { field: CreatedAt,                              sortable: true }
  - { field: UpdatedAt,                              sortable: true }
  - { field: DeletedAt,                              sortable: true }

lookups:
  - fields: [ Handle ]
    description: |-
      searches for page chart by handle (case-insensitive)

  - fields: [ ID ]
    description: |-
      searches for compose page by ID

      It returns compose page even if deleted

rdbms:
  alias: cpg
  table: compose_page
  customFilterConverter: true

