import:
  - github.com/cortezaproject/corteza-server/compose/types

types:
  type: types.Namespace

fields:
  - { field: ID }
  - { field: Name,                                   sortable: true }
  - { field: Slug, lookupFilterPreprocessor: lower,  sortable: true, unique: true }
  - { field: Enabled }
  - { field: Meta, type: "*types.NamespaceMeta" }
  - { field: CreatedAt,                              sortable: true }
  - { field: UpdatedAt,                              sortable: true }
  - { field: DeletedAt,                              sortable: true }

lookups:
  - fields: [ Slug ]
    uniqueConstraintCheck: true
    filter: { DeletedAt: nil }
    description: |-
      searches for namespace by slug (case-insensitive)

  - fields: [ ID ]
    description: |-
      searches for compose namespace by ID

      It returns compose namespace even if deleted

rdbms:
  alias: cns
  table: compose_namespace
  customFilterConverter: true

