import:
  - github.com/cortezaproject/corteza-server/system/types

types:
  type: types.SettingValue
  filterType: types.SettingsFilter

fields:
  - { field: Name, isPrimaryKey: true }
  - { field: OwnedBy, isPrimaryKey: true, column: rel_owner }
  - { field: Value }
  - { field: UpdatedBy }
  - { field: UpdatedAt }

lookups:
  - fields: [ Name, OwnedBy ]
    description: |-
      searches for settings by name and owner

search:
  enablePaging: false
  enableSorting: false

rdbms:
  alias: st
  table: settings
  customFilterConverter: true

