// This is a autogenerated file
//
// Generated from:
//  - corteza-server/src/{{$.Service}}/service/events.yaml
//  - corteza-server/codegen/v2/events/events.gen.adoc.tpl
//
// To regenerate:
// ./event-gen --service {{$.Service}} --docs ../corteza-docs/src/extdev/development/events/
//

= {{ $.ResourceString }}


.List of events on `{{ $.ResourceString }}`
{{- range $event := makeEvents $.Events }}
- `{{ $event }}`
{{- end }}

.Event arguments for `{{ $.ResourceString }}`
[%header,cols=3*]
|===
|Name
|Type
|Immutable

{{- range $p := $.Events.Properties }}
|`{{ camelCase $p.Name }}`
|`{{ $p.Type }}`
|{{ $p.Immutable }}
{{- end }}
|===
