namespace: service-solution
records:
  Department:
  - (envoy): { skipIf: "!missing" }
    values:
      Name: "Service"
      HourCost: "50"
  Settings:
  - (envoy): { skipIf: "!missing" }
    values:
      KBNextNumber: "1"
      DefaultCostPerHour: "50"
      DefaultTimeUpdate: "0.25"
