= Web applications

Rationale behind `/webapp/...` tools is to allow backend developers to quickly test the server with the
unified web application. Tools (see Makefile) download and install unstable (can be changed with `VERSION` var).

.Downloads and installs the webapp under webapp/public using current version
[source,shell]
----
make
----

.Downloads and installs the webapp under webapp/public using specific version
[source,shell]
----
make VERSION=2021.3.3
----

. All available make targets
[cols="2m,5a"]
|===
|target|

| all
| default target alias for install-packages

| install-packages
| downloads and installs the webapp package

| download
| downloads the webapp package

| install-fresh
| builds and installs the webapp from source

| build
| builds the webapp from source

| clean
| removes the package of the current version

| cleaner
| removes all

|===


To enable serving of webapps from the server, make sure `HTTP_WEBAPP_ENABLED` is set to `true`.
This will prefix all API endpoints with `/api/`.

See `HTTP_API_BASE_URL`, `HTTP_WEBAPP_ENABLED`, `HTTP_WEBAPP_BASE_URL`, `HTTP_WEBAPP_BASE_DIR` for
details
