import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faCheck,
  faTimes,
  faHome,
  faSave,
  faKeyboard,
  faMouse,
  faCog,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faExclamationTriangle,
  faSearchPlus,
  faSearchMinus,
  faThumbtack,
  faGripHorizontal,
  faSearch,
  faExpandAlt,
  faPlus,
  faQuestion,
  faAngleDoubleLeft,
  faAngleRight,
  faAngleLeft,
  faEllipsisV,
} from '@fortawesome/free-solid-svg-icons'

import {
  faEdit,
  faTrashAlt,
  faQuestionCircle,
  faUser,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  faEdit,
  faTrashAlt,
  faCheck,
  faTimes,
  faHome,
  faSave,
  faKeyboard,
  faMouse,
  faCog,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faExclamationTriangle,
  faQuestionCircle,
  faSearchPlus,
  faSearchMinus,
  faUser,
  faThumbtack,
  faSearch,
  faGripHorizontal,
  faExpandAlt,
  faPlus,
  faQuestion,
  faAngleDoubleLeft,
  faAngleRight,
  faAngleLeft,
  faEllipsisV,
)
