.PHONY: dev build preview test lint format

dev:
	@pnpm install && pnpm dev

build:
	@pnpm build

preview:
	@pnpm preview

test:
	@pnpm test:unit

lint:
	@pnpm lint

format:
	@pnpm format

.DEFAULT_GOAL := dev
