package inputguard

var phrasesFR = []string{
	"ignorer les instructions précédentes",
	"ignorer les instructions precedentes",
	"ignore tout ce qui précède",
	"ignore tout ce qui precede",
	"oublier tout",
	"oublie tout",
	"tu es maintenant",
	"agis comme",
	"agissez comme",
	"fais semblant d'être",
	"fais semblant d'etre",
	"prétends être",
	"pretends etre",
	"ne suis pas",
	"remplace tes",
	"contourne tes",
	"désormais tu",
	"desormais tu",
	"joue le rôle de",
	"joue le role de",
	"imite",
	"tu es un",
	"tu es une",
	"comporte-toi comme",
	"réponds comme",
	"reponds comme",
}
