package inputguard

var phrasesEN = []string{
	"ignore previous",
	"ignore all previous",
	"ignore above",
	"disregard all",
	"disregard previous",
	"forget everything",
	"you are now",
	"pretend to be",
	"do not follow your",
	"do not follow the previous",
	"do not follow any previous",
	"override your",
	"bypass your",
	"from now on you",
	"role play as",
	"roleplay as",
	"play the role",
	"take on the role",
	"simulate being",
	"impersonate",
	"you are a",
	"behave as a",
	"behave as an",
	"behave as if",
	"respond as a",
	"respond as an",
	"respond as if",
}
