package inputguard

var phrasesPT = []string{
	"ignorar instruções anteriores",
	"ignorar instrucoes anteriores",
	"ignore tudo acima",
	"esqueça tudo",
	"esqueca tudo",
	"agora você é",
	"agora voce e",
	"aja como",
	"atue como",
	"finja ser",
	"simule ser",
	"não siga",
	"nao siga",
	"substitua suas",
	"ignore suas",
	"a partir de agora",
	"interprete o papel de",
	"faça o papel de",
	"faca o papel de",
	"imite",
	"você é um",
	"voce e um",
	"você é uma",
	"voce e uma",
	"comporte-se como",
	"responda como",
}
