blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://forum.cortezaproject.org/
    about: Please ask and answer questions here.
  - name: Ideas, enhancements and feature requests 🚀
    url: https://github.com/orgs/cortezaproject/discussions
    about: Please open a new discussion and describe the idea you have.