package expr

// This file is auto-generated.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//
// Definitions file that controls how this file is generated:
//  - pkg/expr/expr_functions.yaml

// builtInFunctionNames lists every function the expression language registers.
var builtInFunctionNames = map[string]struct{}{
	"abs":           {},
	"average":       {},
	"base64encode":  {},
	"camelize":      {},
	"ceil":          {},
	"coalesce":      {},
	"count":         {},
	"earliest":      {},
	"filter":        {},
	"find":          {},
	"float":         {},
	"floor":         {},
	"format":        {},
	"has":           {},
	"hasAll":        {},
	"hasPrefix":     {},
	"hasSubstring":  {},
	"hasSuffix":     {},
	"int":           {},
	"isEmail":       {},
	"isEmpty":       {},
	"isLeapYear":    {},
	"isNil":         {},
	"isUrl":         {},
	"isWeekDay":     {},
	"join":          {},
	"latest":        {},
	"length":        {},
	"log":           {},
	"longest":       {},
	"match":         {},
	"max":           {},
	"merge":         {},
	"min":           {},
	"modDate":       {},
	"modMonth":      {},
	"modTime":       {},
	"modWeek":       {},
	"modYear":       {},
	"now":           {},
	"omit":          {},
	"parseDuration": {},
	"parseISOTime":  {},
	"pop":           {},
	"pow":           {},
	"push":          {},
	"random":        {},
	"repeat":        {},
	"replace":       {},
	"round":         {},
	"set":           {},
	"shift":         {},
	"shorten":       {},
	"shortest":      {},
	"snakify":       {},
	"sort":          {},
	"splice":        {},
	"split":         {},
	"sqrt":          {},
	"strftime":      {},
	"sub":           {},
	"substring":     {},
	"sum":           {},
	"title":         {},
	"toJSON":        {},
	"toLower":       {},
	"toUpper":       {},
	"trim":          {},
	"trimLeft":      {},
	"trimRight":     {},
	"untitle":       {},
}
