// Catalog of supported connections — mirrors the Admin connection catalog.
// Picking one adds a connection of that type to the project; credentials and
// real config are set later in Admin. `id` is the catalog id (catalogID).

export const CONNECTORS = [
  { id: 'planetcrust:marketo-v1', label: 'Marketo', icon: 'pi pi-megaphone', description: "Marketo's marketing automation platform.", tags: ['marketing', 'automation', 'crm'] },
  { id: 'planetcrust:github', label: 'GitHub', icon: 'pi pi-github', description: 'Repositories, issues, pull requests and more.', tags: ['version-control', 'development'] },
  { id: 'planetcrust:google-sheets-v4', label: 'Google Sheets', icon: 'pi pi-table', description: 'Read and write spreadsheet data.', tags: ['spreadsheet', 'google', 'data'] },
  { id: 'planetcrust:xero-api-v2', label: 'Xero API', icon: 'pi pi-money-bill', description: 'Invoices, contacts and financial data.', tags: ['accounting', 'finance'] },
  { id: 'planetcrust:zendesk-rest-api-v2', label: 'Zendesk REST API', icon: 'pi pi-ticket', description: 'Tickets, users and support resources.', tags: ['support'] },
  { id: 'planetcrust:netsuite-api-v2026', label: 'NetSuite API', icon: 'pi pi-building', description: "NetSuite's REST API for business operations.", tags: ['erp'] },
  { id: 'planetcrust:notion-api-v1', label: 'Notion API', icon: 'pi pi-file', description: 'Databases, pages and more.', tags: ['docs'] },
  { id: 'planetcrust:discord', label: 'Discord', icon: 'pi pi-discord', description: 'Servers, channels and messages.', tags: ['chat'] },
  { id: 'planetcrust:toggl-track-v1', label: 'Toggl Track', icon: 'pi pi-calendar', description: 'Time tracking and reporting.', tags: ['time'] },
  { id: 'planetcrust:bamboohr', label: 'BambooHR', icon: 'pi pi-building', description: 'Employee data, time tracking and HR workflows.', tags: ['hr'] },
  { id: 'planetcrust:twilio', label: 'Twilio', icon: 'pi pi-phone', description: "Twilio's communication APIs.", tags: ['comms', 'sms'] },
  { id: 'planetcrust:tableau-v1', label: 'Tableau', icon: 'pi pi-chart-bar', description: 'Data visualization and BI.', tags: ['analytics'] },
  { id: 'planetcrust:gmail-v1', label: 'Gmail', icon: 'pi pi-envelope', description: 'Send, receive and manage email.', tags: ['email', 'google'] },
  { id: 'planetcrust:wordpress-v2', label: 'WordPress', icon: 'pi pi-globe', description: 'Posts, pages and other content.', tags: ['cms'] },
  { id: 'planetcrust:google-tasks-individual-v1', label: 'Google Tasks', icon: 'pi pi-check-square', description: 'Task lists and tasks.', tags: ['tasks', 'google'] },
  { id: 'planetcrust:canva', label: 'Canva', icon: 'pi pi-palette', description: 'Designs, templates and assets.', tags: ['design'] },
  { id: 'planetcrust:freshdesk-api-v2', label: 'Freshdesk', icon: 'pi pi-ticket', description: 'Ticket management and customer support.', tags: ['support'] },
  { id: 'planetcrust:sinch', label: 'Sinch', icon: 'pi pi-phone', description: 'SMS, voice and verification services.', tags: ['comms'] },
  { id: 'planetcrust:datadog', label: 'Datadog', icon: 'pi pi-chart-line', description: 'Monitoring, analytics and event tracking.', tags: ['monitoring'] },
  { id: 'planetcrust:hubspot-v3', label: 'HubSpot', icon: 'pi pi-megaphone', description: 'Contacts, companies, deals and more.', tags: ['crm'] },
  { id: 'planetcrust:trello-api-v1', label: 'Trello API', icon: 'pi pi-list', description: 'Boards, lists, cards and more.', tags: ['tasks'] },
  { id: 'planetcrust:zoom-api', label: 'Zoom API', icon: 'pi pi-video', description: 'Meetings, webinars and users.', tags: ['comms'] },
  { id: 'planetcrust:bluesky-v1', label: 'Bluesky', icon: 'pi pi-comments', description: 'Posts, users and feeds.', tags: ['social'] },
  { id: 'planetcrust:mistral-ai', label: 'Mistral AI', icon: 'pi pi-sparkles', description: "Mistral AI's API services.", tags: ['ai'] },
  { id: 'planetcrust:hootsuite', label: 'Hootsuite', icon: 'pi pi-megaphone', description: 'Social media content and scheduling.', tags: ['social'] },
  { id: 'planetcrust:mailchimp-v3', label: 'Mailchimp', icon: 'pi pi-envelope', description: 'Audiences, campaigns and automation.', tags: ['marketing', 'email'] },
  { id: 'planetcrust:chatgpt-v1', label: 'ChatGPT', icon: 'pi pi-sparkles', description: "OpenAI's ChatGPT API.", tags: ['ai'] },
  { id: 'planetcrust:google-drive-individual-v3', label: 'Google Drive', icon: 'pi pi-google', description: 'Files and folders in Drive.', tags: ['storage', 'google'] },
  { id: 'planetcrust:shopify-v2026-03', label: 'Shopify', icon: 'pi pi-shopping-cart', description: 'Products, orders, customers and more.', tags: ['ecommerce'] },
  { id: 'planetcrust:stripe-api-v1', label: 'Stripe API', icon: 'pi pi-credit-card', description: 'Payment processing and financial operations.', tags: ['payments'] },
  { id: 'planetcrust:webflow', label: 'Webflow', icon: 'pi pi-globe', description: 'Sites, collections and items.', tags: ['cms'] },
  { id: 'planetcrust:telegram', label: 'Telegram', icon: 'pi pi-telegram', description: 'Messages, chats and bots.', tags: ['chat'] },
  { id: 'planetcrust:docusign-v2', label: 'DocuSign', icon: 'pi pi-file-edit', description: 'Electronic signatures and agreements.', tags: ['esign'] },
  { id: 'planetcrust:figma', label: 'Figma', icon: 'pi pi-palette', description: 'Design files, comments and projects.', tags: ['design'] },
  { id: 'planetcrust:gitlab', label: 'GitLab', icon: 'pi pi-github', description: 'Repositories, CI/CD and issue tracking.', tags: ['version-control'] },
  { id: 'planetcrust:asana-api-v1', label: 'Asana', icon: 'pi pi-list', description: 'Tasks, projects and teams.', tags: ['tasks'] },
  { id: 'planetcrust:clickup', label: 'ClickUp', icon: 'pi pi-list', description: 'Tasks, projects and workflows.', tags: ['tasks'] },
  { id: 'planetcrust:jotform-v1', label: 'Jotform', icon: 'pi pi-file-edit', description: 'Forms, submissions and reports.', tags: ['forms'] },
  { id: 'planetcrust:claude-api', label: 'Claude API', icon: 'pi pi-sparkles', description: "Anthropic's Claude API.", tags: ['ai'] },
  { id: 'planetcrust:google-calendar-individual-v3', label: 'Google Calendar', icon: 'pi pi-calendar', description: 'Events, calendars and reminders.', tags: ['calendar', 'google'] },
]

export const connector = id => CONNECTORS.find(c => c.id === id)
