// Catalog of supported connections — mirrors the Admin connection catalog.
// Picking one adds a connection of that type to the project; credentials and
// real config are set later in Admin. `id` is the catalog id (catalogID).
// `label` is a brand name (proper noun, untranslated); `descriptionKey` is an
// i18n key resolved with $t for display.

export const CONNECTORS = [
  {
    id: 'planetcrust:marketo-v1',
    label: 'Marketo',
    icon: 'pi pi-megaphone',
    descriptionKey: 'project.connectors.marketo',
    tags: ['marketing', 'automation', 'crm'],
  },
  {
    id: 'planetcrust:github',
    label: 'GitHub',
    icon: 'pi pi-github',
    descriptionKey: 'project.connectors.github',
    tags: ['version-control', 'development'],
  },
  {
    id: 'planetcrust:google-sheets-v4',
    label: 'Google Sheets',
    icon: 'pi pi-table',
    descriptionKey: 'project.connectors.googleSheets',
    tags: ['spreadsheet', 'google', 'data'],
  },
  {
    id: 'planetcrust:xero-api-v2',
    label: 'Xero API',
    icon: 'pi pi-money-bill',
    descriptionKey: 'project.connectors.xero',
    tags: ['accounting', 'finance'],
  },
  {
    id: 'planetcrust:zendesk-rest-api-v2',
    label: 'Zendesk REST API',
    icon: 'pi pi-ticket',
    descriptionKey: 'project.connectors.zendesk',
    tags: ['support'],
  },
  {
    id: 'planetcrust:netsuite-api-v2026',
    label: 'NetSuite API',
    icon: 'pi pi-building',
    descriptionKey: 'project.connectors.netsuite',
    tags: ['erp'],
  },
  {
    id: 'planetcrust:notion-api-v1',
    label: 'Notion API',
    icon: 'pi pi-file',
    descriptionKey: 'project.connectors.notion',
    tags: ['docs'],
  },
  {
    id: 'planetcrust:discord',
    label: 'Discord',
    icon: 'pi pi-discord',
    descriptionKey: 'project.connectors.discord',
    tags: ['chat'],
  },
  {
    id: 'planetcrust:toggl-track-v1',
    label: 'Toggl Track',
    icon: 'pi pi-calendar',
    descriptionKey: 'project.connectors.toggl',
    tags: ['time'],
  },
  {
    id: 'planetcrust:bamboohr',
    label: 'BambooHR',
    icon: 'pi pi-building',
    descriptionKey: 'project.connectors.bamboohr',
    tags: ['hr'],
  },
  {
    id: 'planetcrust:twilio',
    label: 'Twilio',
    icon: 'pi pi-phone',
    descriptionKey: 'project.connectors.twilio',
    tags: ['comms', 'sms'],
  },
  {
    id: 'planetcrust:tableau-v1',
    label: 'Tableau',
    icon: 'pi pi-chart-bar',
    descriptionKey: 'project.connectors.tableau',
    tags: ['analytics'],
  },
  {
    id: 'planetcrust:gmail-v1',
    label: 'Gmail',
    icon: 'pi pi-envelope',
    descriptionKey: 'project.connectors.gmail',
    tags: ['email', 'google'],
  },
  {
    id: 'planetcrust:wordpress-v2',
    label: 'WordPress',
    icon: 'pi pi-globe',
    descriptionKey: 'project.connectors.wordpress',
    tags: ['cms'],
  },
  {
    id: 'planetcrust:google-tasks-individual-v1',
    label: 'Google Tasks',
    icon: 'pi pi-check-square',
    descriptionKey: 'project.connectors.googleTasks',
    tags: ['tasks', 'google'],
  },
  {
    id: 'planetcrust:canva',
    label: 'Canva',
    icon: 'pi pi-palette',
    descriptionKey: 'project.connectors.canva',
    tags: ['design'],
  },
  {
    id: 'planetcrust:freshdesk-api-v2',
    label: 'Freshdesk',
    icon: 'pi pi-ticket',
    descriptionKey: 'project.connectors.freshdesk',
    tags: ['support'],
  },
  {
    id: 'planetcrust:sinch',
    label: 'Sinch',
    icon: 'pi pi-phone',
    descriptionKey: 'project.connectors.sinch',
    tags: ['comms'],
  },
  {
    id: 'planetcrust:datadog',
    label: 'Datadog',
    icon: 'pi pi-chart-line',
    descriptionKey: 'project.connectors.datadog',
    tags: ['monitoring'],
  },
  {
    id: 'planetcrust:hubspot-v3',
    label: 'HubSpot',
    icon: 'pi pi-megaphone',
    descriptionKey: 'project.connectors.hubspot',
    tags: ['crm'],
  },
  {
    id: 'planetcrust:trello-api-v1',
    label: 'Trello API',
    icon: 'pi pi-list',
    descriptionKey: 'project.connectors.trello',
    tags: ['tasks'],
  },
  {
    id: 'planetcrust:zoom-api',
    label: 'Zoom API',
    icon: 'pi pi-video',
    descriptionKey: 'project.connectors.zoom',
    tags: ['comms'],
  },
  {
    id: 'planetcrust:bluesky-v1',
    label: 'Bluesky',
    icon: 'pi pi-comments',
    descriptionKey: 'project.connectors.bluesky',
    tags: ['social'],
  },
  {
    id: 'planetcrust:mistral-ai',
    label: 'Mistral AI',
    icon: 'pi pi-sparkles',
    descriptionKey: 'project.connectors.mistral',
    tags: ['ai'],
  },
  {
    id: 'planetcrust:hootsuite',
    label: 'Hootsuite',
    icon: 'pi pi-megaphone',
    descriptionKey: 'project.connectors.hootsuite',
    tags: ['social'],
  },
  {
    id: 'planetcrust:mailchimp-v3',
    label: 'Mailchimp',
    icon: 'pi pi-envelope',
    descriptionKey: 'project.connectors.mailchimp',
    tags: ['marketing', 'email'],
  },
  {
    id: 'planetcrust:chatgpt-v1',
    label: 'ChatGPT',
    icon: 'pi pi-sparkles',
    descriptionKey: 'project.connectors.chatgpt',
    tags: ['ai'],
  },
  {
    id: 'planetcrust:google-drive-individual-v3',
    label: 'Google Drive',
    icon: 'pi pi-google',
    descriptionKey: 'project.connectors.googleDrive',
    tags: ['storage', 'google'],
  },
  {
    id: 'planetcrust:shopify-v2026-03',
    label: 'Shopify',
    icon: 'pi pi-shopping-cart',
    descriptionKey: 'project.connectors.shopify',
    tags: ['ecommerce'],
  },
  {
    id: 'planetcrust:stripe-api-v1',
    label: 'Stripe API',
    icon: 'pi pi-credit-card',
    descriptionKey: 'project.connectors.stripe',
    tags: ['payments'],
  },
  {
    id: 'planetcrust:webflow',
    label: 'Webflow',
    icon: 'pi pi-globe',
    descriptionKey: 'project.connectors.webflow',
    tags: ['cms'],
  },
  {
    id: 'planetcrust:telegram',
    label: 'Telegram',
    icon: 'pi pi-telegram',
    descriptionKey: 'project.connectors.telegram',
    tags: ['chat'],
  },
  {
    id: 'planetcrust:docusign-v2',
    label: 'DocuSign',
    icon: 'pi pi-file-edit',
    descriptionKey: 'project.connectors.docusign',
    tags: ['esign'],
  },
  {
    id: 'planetcrust:figma',
    label: 'Figma',
    icon: 'pi pi-palette',
    descriptionKey: 'project.connectors.figma',
    tags: ['design'],
  },
  {
    id: 'planetcrust:gitlab',
    label: 'GitLab',
    icon: 'pi pi-github',
    descriptionKey: 'project.connectors.gitlab',
    tags: ['version-control'],
  },
  {
    id: 'planetcrust:asana-api-v1',
    label: 'Asana',
    icon: 'pi pi-list',
    descriptionKey: 'project.connectors.asana',
    tags: ['tasks'],
  },
  {
    id: 'planetcrust:clickup',
    label: 'ClickUp',
    icon: 'pi pi-list',
    descriptionKey: 'project.connectors.clickup',
    tags: ['tasks'],
  },
  {
    id: 'planetcrust:jotform-v1',
    label: 'Jotform',
    icon: 'pi pi-file-edit',
    descriptionKey: 'project.connectors.jotform',
    tags: ['forms'],
  },
  {
    id: 'planetcrust:claude-api',
    label: 'Claude API',
    icon: 'pi pi-sparkles',
    descriptionKey: 'project.connectors.claude',
    tags: ['ai'],
  },
  {
    id: 'planetcrust:google-calendar-individual-v3',
    label: 'Google Calendar',
    icon: 'pi pi-calendar',
    descriptionKey: 'project.connectors.googleCalendar',
    tags: ['calendar', 'google'],
  },
]

export const connector = id => CONNECTORS.find(c => c.id === id)
