// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail_message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MailMessage struct {
	Header               *MailMessage_Header `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`
	RawBody              []byte              `protobuf:"bytes,15,opt,name=rawBody,proto3" json:"rawBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MailMessage) Reset()         { *m = MailMessage{} }
func (m *MailMessage) String() string { return proto.CompactTextString(m) }
func (*MailMessage) ProtoMessage()    {}
func (*MailMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d142ecb16d253662, []int{0}
}

func (m *MailMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailMessage.Unmarshal(m, b)
}
func (m *MailMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailMessage.Marshal(b, m, deterministic)
}
func (m *MailMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailMessage.Merge(m, src)
}
func (m *MailMessage) XXX_Size() int {
	return xxx_messageInfo_MailMessage.Size(m)
}
func (m *MailMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MailMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MailMessage proto.InternalMessageInfo

func (m *MailMessage) GetHeader() *MailMessage_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MailMessage) GetRawBody() []byte {
	if m != nil {
		return m.RawBody
	}
	return nil
}

// All typified data (date, to, cc, bcc...)
// is extracted and parsed
//
// Simple string values (subject, message-id, ...)
// are kept under Raw
//
type MailMessage_Header struct {
	Date                 *timestamp.Timestamp                        `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	To                   []*MailMessage_Header_MailAddress           `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc                   []*MailMessage_Header_MailAddress           `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                  []*MailMessage_Header_MailAddress           `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	From                 []*MailMessage_Header_MailAddress           `protobuf:"bytes,5,rep,name=from,proto3" json:"from,omitempty"`
	ReplyTo              []*MailMessage_Header_MailAddress           `protobuf:"bytes,6,rep,name=replyTo,proto3" json:"replyTo,omitempty"`
	Raw                  map[string]*MailMessage_Header_HeaderValues `protobuf:"bytes,15,rep,name=raw,proto3" json:"raw,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *MailMessage_Header) Reset()         { *m = MailMessage_Header{} }
func (m *MailMessage_Header) String() string { return proto.CompactTextString(m) }
func (*MailMessage_Header) ProtoMessage()    {}
func (*MailMessage_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_d142ecb16d253662, []int{0, 0}
}

func (m *MailMessage_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailMessage_Header.Unmarshal(m, b)
}
func (m *MailMessage_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailMessage_Header.Marshal(b, m, deterministic)
}
func (m *MailMessage_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailMessage_Header.Merge(m, src)
}
func (m *MailMessage_Header) XXX_Size() int {
	return xxx_messageInfo_MailMessage_Header.Size(m)
}
func (m *MailMessage_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_MailMessage_Header.DiscardUnknown(m)
}

var xxx_messageInfo_MailMessage_Header proto.InternalMessageInfo

func (m *MailMessage_Header) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *MailMessage_Header) GetTo() []*MailMessage_Header_MailAddress {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MailMessage_Header) GetCc() []*MailMessage_Header_MailAddress {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *MailMessage_Header) GetBcc() []*MailMessage_Header_MailAddress {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *MailMessage_Header) GetFrom() []*MailMessage_Header_MailAddress {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MailMessage_Header) GetReplyTo() []*MailMessage_Header_MailAddress {
	if m != nil {
		return m.ReplyTo
	}
	return nil
}

func (m *MailMessage_Header) GetRaw() map[string]*MailMessage_Header_HeaderValues {
	if m != nil {
		return m.Raw
	}
	return nil
}

type MailMessage_Header_MailAddress struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailMessage_Header_MailAddress) Reset()         { *m = MailMessage_Header_MailAddress{} }
func (m *MailMessage_Header_MailAddress) String() string { return proto.CompactTextString(m) }
func (*MailMessage_Header_MailAddress) ProtoMessage()    {}
func (*MailMessage_Header_MailAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_d142ecb16d253662, []int{0, 0, 0}
}

func (m *MailMessage_Header_MailAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailMessage_Header_MailAddress.Unmarshal(m, b)
}
func (m *MailMessage_Header_MailAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailMessage_Header_MailAddress.Marshal(b, m, deterministic)
}
func (m *MailMessage_Header_MailAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailMessage_Header_MailAddress.Merge(m, src)
}
func (m *MailMessage_Header_MailAddress) XXX_Size() int {
	return xxx_messageInfo_MailMessage_Header_MailAddress.Size(m)
}
func (m *MailMessage_Header_MailAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MailMessage_Header_MailAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MailMessage_Header_MailAddress proto.InternalMessageInfo

func (m *MailMessage_Header_MailAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MailMessage_Header_MailAddress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MailMessage_Header_HeaderValues struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailMessage_Header_HeaderValues) Reset()         { *m = MailMessage_Header_HeaderValues{} }
func (m *MailMessage_Header_HeaderValues) String() string { return proto.CompactTextString(m) }
func (*MailMessage_Header_HeaderValues) ProtoMessage()    {}
func (*MailMessage_Header_HeaderValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_d142ecb16d253662, []int{0, 0, 1}
}

func (m *MailMessage_Header_HeaderValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailMessage_Header_HeaderValues.Unmarshal(m, b)
}
func (m *MailMessage_Header_HeaderValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailMessage_Header_HeaderValues.Marshal(b, m, deterministic)
}
func (m *MailMessage_Header_HeaderValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailMessage_Header_HeaderValues.Merge(m, src)
}
func (m *MailMessage_Header_HeaderValues) XXX_Size() int {
	return xxx_messageInfo_MailMessage_Header_HeaderValues.Size(m)
}
func (m *MailMessage_Header_HeaderValues) XXX_DiscardUnknown() {
	xxx_messageInfo_MailMessage_Header_HeaderValues.DiscardUnknown(m)
}

var xxx_messageInfo_MailMessage_Header_HeaderValues proto.InternalMessageInfo

func (m *MailMessage_Header_HeaderValues) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*MailMessage)(nil), "system.MailMessage")
	proto.RegisterType((*MailMessage_Header)(nil), "system.MailMessage.Header")
	proto.RegisterMapType((map[string]*MailMessage_Header_HeaderValues)(nil), "system.MailMessage.Header.RawEntry")
	proto.RegisterType((*MailMessage_Header_MailAddress)(nil), "system.MailMessage.Header.MailAddress")
	proto.RegisterType((*MailMessage_Header_HeaderValues)(nil), "system.MailMessage.Header.HeaderValues")
}

func init() { proto.RegisterFile("mail_message.proto", fileDescriptor_d142ecb16d253662) }

var fileDescriptor_d142ecb16d253662 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x8a, 0xdb, 0x30,
	0x14, 0x85, 0xf1, 0x7f, 0x72, 0x1d, 0x48, 0xd0, 0xa2, 0x08, 0x6f, 0x6a, 0x5a, 0x48, 0xbd, 0x72,
	0xc0, 0xa5, 0x25, 0xa4, 0x14, 0xda, 0x40, 0xa1, 0x14, 0xb2, 0x11, 0xa1, 0x8b, 0xd9, 0x04, 0xc5,
	0x56, 0x32, 0x61, 0xec, 0xc8, 0x48, 0xca, 0x04, 0xbf, 0xe1, 0xbc, 0xc4, 0xbc, 0xcb, 0x60, 0xc9,
	0x86, 0x6c, 0x26, 0xe0, 0x95, 0xcf, 0xbd, 0x9c, 0xef, 0xe8, 0xc0, 0x35, 0xa0, 0x8a, 0x9e, 0xca,
	0x5d, 0xc5, 0xa4, 0xa4, 0x47, 0x96, 0xd6, 0x82, 0x2b, 0x8e, 0x7c, 0xd9, 0x48, 0xc5, 0xaa, 0xe8,
	0xe3, 0x91, 0xf3, 0x63, 0xc9, 0x16, 0x7a, 0xbb, 0xbf, 0x1c, 0x16, 0xea, 0x54, 0x31, 0xa9, 0x68,
	0x55, 0x1b, 0xe3, 0xa7, 0x17, 0x0f, 0xc2, 0x0d, 0x3d, 0x95, 0x1b, 0x83, 0xa3, 0x0c, 0xfc, 0x47,
	0x46, 0x0b, 0x26, 0xb0, 0x1f, 0x5b, 0x49, 0x98, 0x45, 0xa9, 0x49, 0x4a, 0x6f, 0x4c, 0xe9, 0x5f,
	0xed, 0x20, 0x9d, 0x13, 0x61, 0x08, 0x04, 0xbd, 0xae, 0x79, 0xd1, 0xe0, 0x69, 0x6c, 0x25, 0x13,
	0xd2, 0x8f, 0xd1, 0xab, 0x0b, 0xbe, 0x31, 0xa3, 0x14, 0xdc, 0x82, 0x2a, 0x86, 0xad, 0x2e, 0xd6,
	0x14, 0x4b, 0xfb, 0x62, 0xe9, 0xb6, 0x2f, 0x46, 0xb4, 0x0f, 0x7d, 0x07, 0x5b, 0x71, 0x6c, 0xc7,
	0x4e, 0x12, 0x66, 0xf3, 0xf7, 0x4b, 0xe8, 0xd5, 0xef, 0xa2, 0x10, 0x4c, 0x4a, 0x62, 0x2b, 0xde,
	0x72, 0x79, 0x8e, 0x9d, 0x61, 0x5c, 0x9e, 0xa3, 0x25, 0x38, 0xfb, 0x3c, 0xc7, 0xee, 0x20, 0xb0,
	0x45, 0xd0, 0x0a, 0xdc, 0x83, 0xe0, 0x15, 0xf6, 0x06, 0xa1, 0x9a, 0x41, 0xbf, 0x20, 0x10, 0xac,
	0x2e, 0x9b, 0x2d, 0xc7, 0xfe, 0x20, 0xbc, 0xc7, 0xd0, 0x37, 0x70, 0x04, 0xbd, 0xe2, 0xa9, 0xa6,
	0x3f, 0xdf, 0xa1, 0x09, 0xbd, 0xfe, 0x39, 0x2b, 0xd1, 0x90, 0xd6, 0x1f, 0xfd, 0x30, 0x67, 0xef,
	0xe2, 0xda, 0x13, 0x52, 0x23, 0xf5, 0x81, 0xc6, 0xa4, 0x1f, 0x11, 0x02, 0xf7, 0x4c, 0x2b, 0x86,
	0x6d, 0xbd, 0xd6, 0x3a, 0x9a, 0xc3, 0xc4, 0x84, 0xfe, 0xa7, 0xe5, 0x85, 0x49, 0xf4, 0x01, 0xfc,
	0x67, 0xad, 0xb0, 0x15, 0x3b, 0xc9, 0x98, 0x74, 0x53, 0xb4, 0x83, 0x51, 0xff, 0x2a, 0x9a, 0x81,
	0xf3, 0xc4, 0x9a, 0x2e, 0xbd, 0x95, 0xe8, 0x27, 0x78, 0xda, 0xa7, 0xa3, 0xc3, 0xec, 0xcb, 0x9d,
	0xee, 0xb7, 0xaf, 0x11, 0x43, 0xad, 0xec, 0xa5, 0xf5, 0xcf, 0x1d, 0x05, 0xb3, 0x29, 0xf1, 0x6a,
	0x2a, 0x94, 0x5c, 0x07, 0x0f, 0x9e, 0xf9, 0x9b, 0x7c, 0xfd, 0xf9, 0xfa, 0x16, 0x00, 0x00, 0xff,
	0xff, 0x16, 0x0c, 0x9f, 0x19, 0x19, 0x03, 0x00, 0x00,
}
