// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MakeJWTUserRequest struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeJWTUserRequest) Reset()         { *m = MakeJWTUserRequest{} }
func (m *MakeJWTUserRequest) String() string { return proto.CompactTextString(m) }
func (*MakeJWTUserRequest) ProtoMessage()    {}
func (*MakeJWTUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *MakeJWTUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeJWTUserRequest.Unmarshal(m, b)
}
func (m *MakeJWTUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeJWTUserRequest.Marshal(b, m, deterministic)
}
func (m *MakeJWTUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeJWTUserRequest.Merge(m, src)
}
func (m *MakeJWTUserRequest) XXX_Size() int {
	return xxx_messageInfo_MakeJWTUserRequest.Size(m)
}
func (m *MakeJWTUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeJWTUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeJWTUserRequest proto.InternalMessageInfo

func (m *MakeJWTUserRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type MakeJWTUserResponse struct {
	JWT                  string   `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeJWTUserResponse) Reset()         { *m = MakeJWTUserResponse{} }
func (m *MakeJWTUserResponse) String() string { return proto.CompactTextString(m) }
func (*MakeJWTUserResponse) ProtoMessage()    {}
func (*MakeJWTUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *MakeJWTUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeJWTUserResponse.Unmarshal(m, b)
}
func (m *MakeJWTUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeJWTUserResponse.Marshal(b, m, deterministic)
}
func (m *MakeJWTUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeJWTUserResponse.Merge(m, src)
}
func (m *MakeJWTUserResponse) XXX_Size() int {
	return xxx_messageInfo_MakeJWTUserResponse.Size(m)
}
func (m *MakeJWTUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeJWTUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeJWTUserResponse proto.InternalMessageInfo

func (m *MakeJWTUserResponse) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

type FindByIDUserRequest struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByIDUserRequest) Reset()         { *m = FindByIDUserRequest{} }
func (m *FindByIDUserRequest) String() string { return proto.CompactTextString(m) }
func (*FindByIDUserRequest) ProtoMessage()    {}
func (*FindByIDUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *FindByIDUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIDUserRequest.Unmarshal(m, b)
}
func (m *FindByIDUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIDUserRequest.Marshal(b, m, deterministic)
}
func (m *FindByIDUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIDUserRequest.Merge(m, src)
}
func (m *FindByIDUserRequest) XXX_Size() int {
	return xxx_messageInfo_FindByIDUserRequest.Size(m)
}
func (m *FindByIDUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIDUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIDUserRequest proto.InternalMessageInfo

func (m *FindByIDUserRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type FindByIDUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByIDUserResponse) Reset()         { *m = FindByIDUserResponse{} }
func (m *FindByIDUserResponse) String() string { return proto.CompactTextString(m) }
func (*FindByIDUserResponse) ProtoMessage()    {}
func (*FindByIDUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *FindByIDUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIDUserResponse.Unmarshal(m, b)
}
func (m *FindByIDUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIDUserResponse.Marshal(b, m, deterministic)
}
func (m *FindByIDUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIDUserResponse.Merge(m, src)
}
func (m *FindByIDUserResponse) XXX_Size() int {
	return xxx_messageInfo_FindByIDUserResponse.Size(m)
}
func (m *FindByIDUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIDUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIDUserResponse proto.InternalMessageInfo

func (m *FindByIDUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Handle               string   `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func init() {
	proto.RegisterType((*MakeJWTUserRequest)(nil), "system.MakeJWTUserRequest")
	proto.RegisterType((*MakeJWTUserResponse)(nil), "system.MakeJWTUserResponse")
	proto.RegisterType((*FindByIDUserRequest)(nil), "system.FindByIDUserRequest")
	proto.RegisterType((*FindByIDUserResponse)(nil), "system.FindByIDUserResponse")
	proto.RegisterType((*User)(nil), "system.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xba, 0x49, 0x75, 0x14, 0x91, 0x69, 0x91, 0x25, 0x7a, 0x28, 0xb9, 0xe8, 0x41,
	0x73, 0xa8, 0x17, 0xcf, 0x21, 0x0a, 0x29, 0x78, 0x09, 0x95, 0x82, 0xb7, 0x48, 0x06, 0x0c, 0x4d,
	0x36, 0x35, 0x9b, 0x1e, 0xfa, 0x37, 0xfc, 0xc5, 0xb2, 0x93, 0x6d, 0xa1, 0x98, 0x43, 0x4f, 0x99,
	0xf7, 0xe6, 0xe3, 0xed, 0xcc, 0x04, 0x60, 0xab, 0xa9, 0x8d, 0x36, 0x6d, 0xd3, 0x35, 0xe8, 0xeb,
	0x9d, 0xee, 0xa8, 0x0e, 0x1f, 0x01, 0xdf, 0xf3, 0x35, 0x2d, 0x56, 0xcb, 0x0f, 0x4d, 0x6d, 0x46,
	0x3f, 0x5b, 0xd2, 0x1d, 0xde, 0x80, 0x6f, 0xd8, 0x34, 0x91, 0xce, 0xcc, 0x79, 0x10, 0x99, 0x55,
	0xe1, 0x3d, 0x4c, 0x8e, 0x68, 0xbd, 0x69, 0x94, 0x26, 0xbc, 0x86, 0xd1, 0x62, 0xb5, 0x64, 0xf6,
	0x3c, 0x33, 0x65, 0xf8, 0x04, 0x93, 0xb7, 0x52, 0x15, 0xf1, 0x2e, 0x4d, 0x4e, 0xc9, 0x7d, 0x81,
	0xe9, 0x31, 0x6e, 0x83, 0x67, 0x20, 0x0c, 0xc1, 0xf4, 0xc5, 0xfc, 0x32, 0xea, 0x87, 0x8e, 0x98,
	0xe1, 0x4e, 0x58, 0x81, 0x30, 0x0a, 0xaf, 0xc0, 0x3d, 0xa4, 0xba, 0x69, 0x82, 0x53, 0xf0, 0xa8,
	0xce, 0xcb, 0x4a, 0xba, 0x3c, 0x54, 0x2f, 0xcc, 0xfb, 0xdf, 0xb9, 0x2a, 0x2a, 0x92, 0x23, 0xb6,
	0xad, 0x42, 0x04, 0xa1, 0xf2, 0x9a, 0xa4, 0x60, 0x97, 0x6b, 0xe3, 0xad, 0x4b, 0x55, 0x48, 0xaf,
	0xf7, 0x4c, 0x3d, 0xff, 0x75, 0xc0, 0x33, 0xcf, 0x69, 0x8c, 0x61, 0x6c, 0x2f, 0x81, 0xc1, 0x7e,
	0xac, 0xff, 0x87, 0x0c, 0x6e, 0x07, 0x7b, 0x76, 0xbb, 0x57, 0x38, 0xdb, 0x6f, 0x8d, 0x07, 0x70,
	0xe0, 0x6c, 0xc1, 0xdd, 0x70, 0xb3, 0x8f, 0x89, 0xc7, 0x9f, 0x1e, 0xff, 0xd3, 0x2f, 0x9f, 0x3f,
	0xcf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x54, 0x3b, 0x6a, 0xe8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	MakeJWT(ctx context.Context, in *MakeJWTUserRequest, opts ...grpc.CallOption) (*MakeJWTUserResponse, error)
	FindByID(ctx context.Context, in *FindByIDUserRequest, opts ...grpc.CallOption) (*FindByIDUserResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) MakeJWT(ctx context.Context, in *MakeJWTUserRequest, opts ...grpc.CallOption) (*MakeJWTUserResponse, error) {
	out := new(MakeJWTUserResponse)
	err := c.cc.Invoke(ctx, "/system.Users/MakeJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) FindByID(ctx context.Context, in *FindByIDUserRequest, opts ...grpc.CallOption) (*FindByIDUserResponse, error) {
	out := new(FindByIDUserResponse)
	err := c.cc.Invoke(ctx, "/system.Users/FindByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	MakeJWT(context.Context, *MakeJWTUserRequest) (*MakeJWTUserResponse, error)
	FindByID(context.Context, *FindByIDUserRequest) (*FindByIDUserResponse, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) MakeJWT(ctx context.Context, req *MakeJWTUserRequest) (*MakeJWTUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeJWT not implemented")
}
func (*UnimplementedUsersServer) FindByID(ctx context.Context, req *FindByIDUserRequest) (*FindByIDUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByID not implemented")
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_MakeJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeJWTUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).MakeJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.Users/MakeJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).MakeJWT(ctx, req.(*MakeJWTUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_FindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIDUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).FindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.Users/FindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).FindByID(ctx, req.(*FindByIDUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "system.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeJWT",
			Handler:    _Users_MakeJWT_Handler,
		},
		{
			MethodName: "FindByID",
			Handler:    _Users_FindByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
