version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:1.3.0
    container_name: project_name-opensearch
    environment:
      cluster.name: opensearch-cluster
      node.name: opensearch
      discovery.seed_hosts: project_name-opensearch,project_name-opensearch-node2
      cluster.initial_cluster_manager_nodes: project_name-opensearch,project_name-opensearch-node2
      bootstrap.memory_lock: 'true' # along with the memlock settings below, disables swapping
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      DISABLE_SECURITY_PLUGIN: 'true' # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 512M
        reservations:
          cpus: 0.10
          memory: 128M
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer
    networks:
      - opensearch

  opensearch-node2:
    image: opensearchproject/opensearch:1.3.0
    container_name: project_name-opensearch-node2
    environment:
      cluster.name: opensearch-cluster
      node.name: opensearch-node2
      discovery.seed_hosts: project_name-opensearch,project_name-opensearch-node2
      cluster.initial_cluster_manager_nodes: project_name-opensearch,project_name-opensearch-node2
      bootstrap.memory_lock: 'true'
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      DISABLE_SECURITY_PLUGIN: 'true' # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://project_name-opensearch:9200","http://project_name-opensearch-node2:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true' # disables security dashboards plugin in OpenSearch Dashboards

    networks:
      - opensearch

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch:


