ALTER TABLE `compose_page`
    ADD COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN `updated_at` DATETIME DEFAULT NULL,
    ADD COLUMN `deleted_at` DATETIME DEFAULT NULL;

ALTER TABLE `compose_page` CHANGE COLUMN `module_id` `rel_module` BIGINT UNSIGNED NOT NULL DEFAULT 0;
