export { default as CInputFieldValueMap } from './CInputFieldValueMap.vue'
export { default as CInputSearch } from './CInputSearch.vue'
export { default as CInputText } from './CInputText.vue'
export { default as CInputSelect } from './CInputSelect.vue'
export { default as CInputUser } from './CInputUser.vue'
export { default as CInputNamespace } from './CInputNamespace.vue'
export { default as CInputModule } from './CInputModule.vue'
export { INPUT_REGISTRY, resolveInputComponent } from './registry'
