allow:
  authenticated:
    corteza::compose:namespace/*:
      - read

    corteza::compose:module/*/*:
      - read

    corteza::compose:page/*/*:
      - read

    corteza::compose:chart/*/*:
      - read

  admins:
    corteza::compose/:
      - grant
      - settings.read
      - settings.manage
      - namespace.create

    corteza::compose:namespace/*/*:
      - read
      - update
      - delete
      - manage
      - page.create
      - module.create
      - chart.create

    corteza::compose:module/*/*:
      - read
      - update
      - delete
      - record.create

    corteza::compose:module-field/*/*/*:
      - record.value.read
      - record.value.update

    corteza::compose:record/*/*/*:
      - read
      - update
      - delete

    corteza::compose:chart/*/*:
      - read
      - update
      - delete

    corteza::compose:page/*/*:
      - read
      - update
      - delete

  low_code_admins:
    corteza::compose/:
      - grant
      - settings.read
      - settings.manage
      - namespace.create

    corteza::compose:namespace/*/*:
      - read
      - update
      - delete
      - manage
      - page.create
      - module.create
      - chart.create

    corteza::compose:module/*/*:
      - read
      - update
      - delete
      - record.create

    corteza::compose:module-field/*/*/*:
      - record.value.read
      - record.value.update

    corteza::compose:record/*/*/*:
      - read
      - update
      - delete

    corteza::compose:chart/*/*:
      - read
      - update
      - delete

    corteza::compose:page/*/*:
      - read
      - update
      - delete
