allow:
  authenticated:
    corteza::compose/:
      - namespaces.search

    corteza::compose:namespace/*:
      - read

    corteza::compose:module/*/*:
      - read

    corteza::compose:page/*/*:
      - read

    corteza::compose:chart/*/*:
      - read

# @todo implement support for record resource import in Envoy
#    corteza::compose:record/*/*/*:
#      - read

  admins:
    corteza::compose/:
      - grant
      - settings.read
      - settings.manage
      - namespace.create
      - namespaces.search

    corteza::compose:namespace/*/*:
      - read
      - update
      - delete
      - manage
      - page.create
      - pages.search
      - module.create
      - modules.search
      - chart.create
      - charts.search

    corteza::compose:module/*/*:
      - read
      - update
      - delete
      - record.create
      - records.search

    corteza::compose:module-field/*/*/*:
      - record.value.read
      - record.value.update

# @todo implement support for record resource import in Envoy
#    corteza::compose:record/*/*/*:
#      - read
#      - update
#      - delete

    corteza::compose:chart/*/*:
      - read
      - update
      - delete

    corteza::compose:page/*/*:
      - read
      - update
      - delete

  low_code_admins:
    corteza::compose/:
      - grant
      - settings.read
      - settings.manage
      - namespace.create
      - namespaces.search

    corteza::compose:namespace/*/*:
      - read
      - update
      - delete
      - manage
      - page.create
      - pages.search
      - module.create
      - modules.search
      - chart.create
      - charts.search

    corteza::compose:module/*/*:
      - read
      - update
      - delete
      - record.create
      - records.search

    corteza::compose:module-field/*/*/*:
      - record.value.read
      - record.value.update

# @todo implement support for record resource import in Envoy
#    corteza::compose:record/*/*/*:
#      - read
#      - update
#      - delete

    corteza::compose:chart/*/*:
      - read
      - update
      - delete

    corteza::compose:page/*/*:
      - read
      - update
      - delete
