rbac:
  resource: { references: [] }

  operations:
    grant:
      description: Manage automation permissions

    workflow.create:
      description: Create workflows

    triggers.search:
      description: List, search or filter triggers

    sessions.search:
      description: List, search or filter sessions

    workflows.search:
      description: List, search or filter workflows
