settings:
  messaging.ui.emoji.enabled: true
  messaging.ui.browser-notifications.enabled: true
  messaging.ui.browser-notifications.header: ${user} in ${channel}
  messaging.ui.browser-notifications.message-trim: 200
  messaging.message.attachments.enabled: true
  messaging.message.attachments.max-size: 10
  messaging.message.attachments.mimetypes: []
  messaging.message.attachments.source.gallery.enabled: true
  messaging.message.attachments.source.camera.enabled: true
