settings:
  ui.emoji.enabled: true
  ui.browser-notifications.enabled: true
  ui.browser-notifications.header: ${user} in ${channel}
  ui.browser-notifications.message-trim: 200
  message.attachments.enabled: true
  message.attachments.max-size: 10
  message.attachments.mimetypes: []
  message.attachments.source.gallery.enabled: true
  message.attachments.source.camera.enabled: true
