# build stage
FROM golang:1.19-buster as build-stage

ENV BUILD_OS=linux
ENV BUILD_ARCH=amd64
ENV BUILD_VERSION=latest

WORKDIR /human

COPY . ./

RUN make release-clean release


# deploy stage
FROM ubuntu:22.04

RUN apt-get -y update \
 && apt-get -y install \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

ENV STORAGE_PATH "/data"
#ENV CORREDOR_ADDR "corredor:80"
#ENV HTTP_ADDR "0.0.0.0:80"
#ENV HTTP_WEBAPP_ENABLED "false"
ENV PATH "/human/bin:${PATH}"

WORKDIR /human

VOLUME /data

COPY --from=build-stage /human/build/pkg/human-server ./

HEALTHCHECK --interval=30s --start-period=1m --timeout=30s --retries=3 \
    CMD curl --silent --fail --fail-early http://127.0.0.1:80/healthcheck || exit 1

EXPOSE 80

ENTRYPOINT ["./bin/human-server"]

#CMD ["serve-api"]
