// Code generated by MockGen. DO NOT EDIT.
// Source: sam/service/channel.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	types "github.com/crusttech/crust/messaging/types"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockChannelService is a mock of ChannelService interface
type MockChannelService struct {
	ctrl     *gomock.Controller
	recorder *MockChannelServiceMockRecorder
}

// MockChannelServiceMockRecorder is the mock recorder for MockChannelService
type MockChannelServiceMockRecorder struct {
	mock *MockChannelService
}

// NewMockChannelService creates a new mock instance
func NewMockChannelService(ctrl *gomock.Controller) *MockChannelService {
	mock := &MockChannelService{ctrl: ctrl}
	mock.recorder = &MockChannelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChannelService) EXPECT() *MockChannelServiceMockRecorder {
	return m.recorder
}

// With mocks base method
func (m *MockChannelService) With(ctx context.Context) ChannelService {
	ret := m.ctrl.Call(m, "With", ctx)
	ret0, _ := ret[0].(ChannelService)
	return ret0
}

// With indicates an expected call of With
func (mr *MockChannelServiceMockRecorder) With(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*MockChannelService)(nil).With), ctx)
}

// FindByID mocks base method
func (m *MockChannelService) FindByID(channelID uint64) (*types.Channel, error) {
	ret := m.ctrl.Call(m, "FindByID", channelID)
	ret0, _ := ret[0].(*types.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockChannelServiceMockRecorder) FindByID(channelID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockChannelService)(nil).FindByID), channelID)
}

// Find mocks base method
func (m *MockChannelService) Find(filter *types.ChannelFilter) (types.ChannelSet, error) {
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].(types.ChannelSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockChannelServiceMockRecorder) Find(filter interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockChannelService)(nil).Find), filter)
}

// Create mocks base method
func (m *MockChannelService) Create(channel *types.Channel) (*types.Channel, error) {
	ret := m.ctrl.Call(m, "Create", channel)
	ret0, _ := ret[0].(*types.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockChannelServiceMockRecorder) Create(channel interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChannelService)(nil).Create), channel)
}

// Update mocks base method
func (m *MockChannelService) Update(channel *types.Channel) (*types.Channel, error) {
	ret := m.ctrl.Call(m, "Update", channel)
	ret0, _ := ret[0].(*types.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockChannelServiceMockRecorder) Update(channel interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockChannelService)(nil).Update), channel)
}

// FindMembers mocks base method
func (m *MockChannelService) FindMembers(channelID uint64) (types.ChannelMemberSet, error) {
	ret := m.ctrl.Call(m, "FindMembers", channelID)
	ret0, _ := ret[0].(types.ChannelMemberSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMembers indicates an expected call of FindMembers
func (mr *MockChannelServiceMockRecorder) FindMembers(channelID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMembers", reflect.TypeOf((*MockChannelService)(nil).FindMembers), channelID)
}

// InviteUser mocks base method
func (m *MockChannelService) InviteUser(channelID uint64, memberIDs ...uint64) (types.ChannelMemberSet, error) {
	varargs := []interface{}{channelID}
	for _, a := range memberIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InviteUser", varargs...)
	ret0, _ := ret[0].(types.ChannelMemberSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InviteUser indicates an expected call of InviteUser
func (mr *MockChannelServiceMockRecorder) InviteUser(channelID interface{}, memberIDs ...interface{}) *gomock.Call {
	varargs := append([]interface{}{channelID}, memberIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteUser", reflect.TypeOf((*MockChannelService)(nil).InviteUser), varargs...)
}

// AddMember mocks base method
func (m *MockChannelService) AddMember(channelID uint64, memberIDs ...uint64) (types.ChannelMemberSet, error) {
	varargs := []interface{}{channelID}
	for _, a := range memberIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddMember", varargs...)
	ret0, _ := ret[0].(types.ChannelMemberSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember
func (mr *MockChannelServiceMockRecorder) AddMember(channelID interface{}, memberIDs ...interface{}) *gomock.Call {
	varargs := append([]interface{}{channelID}, memberIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockChannelService)(nil).AddMember), varargs...)
}

// DeleteMember mocks base method
func (m *MockChannelService) DeleteMember(channelID uint64, memberIDs ...uint64) error {
	varargs := []interface{}{channelID}
	for _, a := range memberIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMember", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMember indicates an expected call of DeleteMember
func (mr *MockChannelServiceMockRecorder) DeleteMember(channelID interface{}, memberIDs ...interface{}) *gomock.Call {
	varargs := append([]interface{}{channelID}, memberIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMember", reflect.TypeOf((*MockChannelService)(nil).DeleteMember), varargs...)
}

// Archive mocks base method
func (m *MockChannelService) Archive(ID uint64) (*types.Channel, error) {
	ret := m.ctrl.Call(m, "Archive", ID)
	ret0, _ := ret[0].(*types.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Archive indicates an expected call of Archive
func (mr *MockChannelServiceMockRecorder) Archive(ID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockChannelService)(nil).Archive), ID)
}

// Unarchive mocks base method
func (m *MockChannelService) Unarchive(ID uint64) (*types.Channel, error) {
	ret := m.ctrl.Call(m, "Unarchive", ID)
	ret0, _ := ret[0].(*types.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unarchive indicates an expected call of Unarchive
func (mr *MockChannelServiceMockRecorder) Unarchive(ID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unarchive", reflect.TypeOf((*MockChannelService)(nil).Unarchive), ID)
}

// Delete mocks base method
func (m *MockChannelService) Delete(ID uint64) (*types.Channel, error) {
	ret := m.ctrl.Call(m, "Delete", ID)
	ret0, _ := ret[0].(*types.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *MockChannelServiceMockRecorder) Delete(ID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChannelService)(nil).Delete), ID)
}

// Undelete mocks base method
func (m *MockChannelService) Undelete(ID uint64) (*types.Channel, error) {
	ret := m.ctrl.Call(m, "Undelete", ID)
	ret0, _ := ret[0].(*types.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Undelete indicates an expected call of Undelete
func (mr *MockChannelServiceMockRecorder) Undelete(ID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockChannelService)(nil).Undelete), ID)
}

// RecordView mocks base method
func (m *MockChannelService) RecordView(userID, channelID, lastMessageID uint64) error {
	ret := m.ctrl.Call(m, "RecordView", userID, channelID, lastMessageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordView indicates an expected call of RecordView
func (mr *MockChannelServiceMockRecorder) RecordView(userID, channelID, lastMessageID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordView", reflect.TypeOf((*MockChannelService)(nil).RecordView), userID, channelID, lastMessageID)
}
