import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faGripHorizontal,
  faThumbtack,
  faHome,
  faChevronLeft,
  faChevronRight,
  faThLarge,
  faCheck,
  faCheckDouble,
  faTimes,
  faAngleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faSearch,
  faBellSlash,
  faBell as faBellSolid,
  faEllipsisV,
} from '@fortawesome/free-solid-svg-icons'

import {
  faUser,
  faQuestionCircle,
  faBell,
  faTrashAlt,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  faHome,
  faThLarge,
  faUser,
  faThumbtack,
  faQuestionCircle,
  faChevronLeft,
  faChevronRight,
  faGripHorizontal,
  faCheck,
  faCheckDouble,
  faTimes,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faSearch,
  faAngleUp,
  faAngleDown,
  faBell,
  faBellSolid,
  faBellSlash,
  faEllipsisV,
  faTrashAlt,
)
