// Code generated by protoc-gen-go. DO NOT EDIT.
// source: module.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Module struct {
	ModuleID             uint64               `protobuf:"varint,1,opt,name=moduleID,proto3" json:"moduleID,omitempty"`
	NamespaceID          uint64               `protobuf:"varint,2,opt,name=namespaceID,proto3" json:"namespaceID,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	Fields               []*ModuleField       `protobuf:"bytes,15,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{0}
}

func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetModuleID() uint64 {
	if m != nil {
		return m.ModuleID
	}
	return 0
}

func (m *Module) GetNamespaceID() uint64 {
	if m != nil {
		return m.NamespaceID
	}
	return 0
}

func (m *Module) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Module) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Module) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Module) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Module) GetFields() []*ModuleField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ModuleField struct {
	FieldID              uint64   `protobuf:"varint,1,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	IsMulti              bool     `protobuf:"varint,4,opt,name=isMulti,proto3" json:"isMulti,omitempty"`
	IsPrivate            bool     `protobuf:"varint,5,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	IsVisible            bool     `protobuf:"varint,6,opt,name=isVisible,proto3" json:"isVisible,omitempty"`
	IsRequired           bool     `protobuf:"varint,7,opt,name=isRequired,proto3" json:"isRequired,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleField) Reset()         { *m = ModuleField{} }
func (m *ModuleField) String() string { return proto.CompactTextString(m) }
func (*ModuleField) ProtoMessage()    {}
func (*ModuleField) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{1}
}

func (m *ModuleField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleField.Unmarshal(m, b)
}
func (m *ModuleField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleField.Marshal(b, m, deterministic)
}
func (m *ModuleField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleField.Merge(m, src)
}
func (m *ModuleField) XXX_Size() int {
	return xxx_messageInfo_ModuleField.Size(m)
}
func (m *ModuleField) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleField.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleField proto.InternalMessageInfo

func (m *ModuleField) GetFieldID() uint64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *ModuleField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleField) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ModuleField) GetIsMulti() bool {
	if m != nil {
		return m.IsMulti
	}
	return false
}

func (m *ModuleField) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *ModuleField) GetIsVisible() bool {
	if m != nil {
		return m.IsVisible
	}
	return false
}

func (m *ModuleField) GetIsRequired() bool {
	if m != nil {
		return m.IsRequired
	}
	return false
}

func init() {
	proto.RegisterType((*Module)(nil), "compose.Module")
	proto.RegisterType((*ModuleField)(nil), "compose.ModuleField")
}

func init() { proto.RegisterFile("module.proto", fileDescriptor_ae7704718fb7daeb) }

var fileDescriptor_ae7704718fb7daeb = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xd6, 0xb5, 0xeb, 0xab, 0x20, 0x04, 0x0f, 0x61, 0x88, 0x96, 0x9d, 0x7a, 0x90,
	0x0e, 0xe6, 0xc5, 0xab, 0x22, 0x82, 0x87, 0x81, 0x14, 0xf1, 0xe0, 0xad, 0x5b, 0xde, 0x46, 0x30,
	0x5d, 0x6a, 0x93, 0xfa, 0xa7, 0xf9, 0x1f, 0xf8, 0x7f, 0x49, 0x92, 0xa6, 0xeb, 0x6d, 0xa7, 0xe4,
	0x7d, 0xbf, 0xef, 0x7b, 0x3c, 0x3e, 0xb8, 0xa8, 0x25, 0xeb, 0x04, 0x16, 0x4d, 0x2b, 0xb5, 0x24,
	0xf1, 0x4e, 0xd6, 0x8d, 0x54, 0xb8, 0xb8, 0x3d, 0x48, 0x79, 0x10, 0xb8, 0xb2, 0xf2, 0xb6, 0xdb,
	0xaf, 0x34, 0xaf, 0x51, 0xe9, 0xaa, 0x6e, 0x9c, 0x73, 0xf9, 0x3b, 0x81, 0x68, 0x63, 0xa3, 0x64,
	0x01, 0x73, 0xb7, 0xe4, 0xf5, 0x99, 0x06, 0x59, 0x90, 0x87, 0xe5, 0x30, 0x93, 0x0c, 0xd2, 0x63,
	0x55, 0xa3, 0x6a, 0xaa, 0x9d, 0xc1, 0x13, 0x8b, 0xc7, 0x12, 0x21, 0x10, 0x9a, 0x91, 0x4e, 0xb3,
	0x20, 0x4f, 0x4a, 0xfb, 0x27, 0x0f, 0x90, 0xec, 0x5a, 0xac, 0x34, 0xb2, 0x47, 0x4d, 0xe7, 0x59,
	0x90, 0xa7, 0xeb, 0x45, 0xe1, 0x2e, 0x2a, 0xfc, 0x45, 0xc5, 0xbb, 0xbf, 0xa8, 0x3c, 0x99, 0x4d,
	0xb2, 0x6b, 0x58, 0x9f, 0x4c, 0xce, 0x27, 0x07, 0xb3, 0x49, 0x32, 0x14, 0xe8, 0x92, 0x70, 0x3e,
	0x39, 0x98, 0xc9, 0x1d, 0x44, 0x7b, 0x8e, 0x82, 0x29, 0x7a, 0x99, 0x4d, 0xf3, 0x74, 0x7d, 0x55,
	0xf4, 0x2d, 0x16, 0xae, 0xa0, 0x17, 0x03, 0xcb, 0xde, 0xb3, 0xfc, 0x0b, 0x20, 0x1d, 0xe9, 0x84,
	0x42, 0x6c, 0xc9, 0x50, 0x9e, 0x1f, 0x87, 0x66, 0x26, 0xa3, 0x66, 0x08, 0x84, 0x5f, 0xfc, 0xc8,
	0x7c, 0x5b, 0xe6, 0x6f, 0x36, 0x70, 0xb5, 0xe9, 0x84, 0xe6, 0x34, 0xcc, 0x82, 0x7c, 0x5e, 0xfa,
	0x91, 0x5c, 0x43, 0xc2, 0xd5, 0x5b, 0xcb, 0x7f, 0x2a, 0x8d, 0x74, 0x66, 0xd9, 0x49, 0x70, 0xf4,
	0x83, 0x2b, 0xbe, 0x15, 0x48, 0x23, 0x4f, 0x7b, 0x81, 0xdc, 0x00, 0x70, 0x55, 0xe2, 0x77, 0xc7,
	0x5b, 0x64, 0x34, 0xb6, 0x78, 0xa4, 0x3c, 0xc5, 0x9f, 0x33, 0x57, 0x4b, 0x64, 0x9f, 0xfb, 0xff,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x5f, 0x7a, 0xe9, 0x4a, 0x02, 0x00, 0x00,
}
