// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	RecordID             uint64               `protobuf:"varint,1,opt,name=recordID,proto3" json:"recordID,omitempty"`
	ModuleID             uint64               `protobuf:"varint,2,opt,name=moduleID,proto3" json:"moduleID,omitempty"`
	NamespaceID          uint64               `protobuf:"varint,3,opt,name=namespaceID,proto3" json:"namespaceID,omitempty"`
	OwnedBy              uint64               `protobuf:"varint,4,opt,name=ownedBy,proto3" json:"ownedBy,omitempty"`
	CreatedBy            uint64               `protobuf:"varint,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy            uint64               `protobuf:"varint,6,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	DeletedBy            uint64               `protobuf:"varint,7,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	Values               []*RecordValue       `protobuf:"bytes,15,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetRecordID() uint64 {
	if m != nil {
		return m.RecordID
	}
	return 0
}

func (m *Record) GetModuleID() uint64 {
	if m != nil {
		return m.ModuleID
	}
	return 0
}

func (m *Record) GetNamespaceID() uint64 {
	if m != nil {
		return m.NamespaceID
	}
	return 0
}

func (m *Record) GetOwnedBy() uint64 {
	if m != nil {
		return m.OwnedBy
	}
	return 0
}

func (m *Record) GetCreatedBy() uint64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *Record) GetUpdatedBy() uint64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *Record) GetDeletedBy() uint64 {
	if m != nil {
		return m.DeletedBy
	}
	return 0
}

func (m *Record) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Record) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Record) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Record) GetValues() []*RecordValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type RecordValue struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordValue) Reset()         { *m = RecordValue{} }
func (m *RecordValue) String() string { return proto.CompactTextString(m) }
func (*RecordValue) ProtoMessage()    {}
func (*RecordValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{1}
}

func (m *RecordValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordValue.Unmarshal(m, b)
}
func (m *RecordValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordValue.Marshal(b, m, deterministic)
}
func (m *RecordValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordValue.Merge(m, src)
}
func (m *RecordValue) XXX_Size() int {
	return xxx_messageInfo_RecordValue.Size(m)
}
func (m *RecordValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordValue.DiscardUnknown(m)
}

var xxx_messageInfo_RecordValue proto.InternalMessageInfo

func (m *RecordValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecordValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Record)(nil), "compose.Record")
	proto.RegisterType((*RecordValue)(nil), "compose.RecordValue")
}

func init() { proto.RegisterFile("record.proto", fileDescriptor_bf94fd919e302a1d) }

var fileDescriptor_bf94fd919e302a1d = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x3f, 0x6b, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0xfd, 0x2f, 0x3e, 0x17, 0x0a, 0x22, 0x83, 0x30, 0x85, 0x9a, 0x4c, 0x1e, 0x8a,
	0x02, 0xe9, 0xd0, 0xae, 0x0e, 0x59, 0xb2, 0x8a, 0xd2, 0xa1, 0x9b, 0x6b, 0x5f, 0x43, 0xc1, 0x8e,
	0x8c, 0x2d, 0xb7, 0xf4, 0x6b, 0xf5, 0x13, 0x16, 0x9d, 0x6c, 0x25, 0x5b, 0x26, 0xfb, 0xde, 0xef,
	0x3d, 0x49, 0xdc, 0x83, 0xdb, 0x1e, 0x2b, 0xd5, 0xd7, 0xa2, 0xeb, 0x95, 0x56, 0x2c, 0xaa, 0x54,
	0xdb, 0xa9, 0x01, 0xd3, 0x87, 0xa3, 0x52, 0xc7, 0x06, 0x37, 0x24, 0x7f, 0x8c, 0x9f, 0x1b, 0xfd,
	0xd5, 0xe2, 0xa0, 0xcb, 0xb6, 0xb3, 0xce, 0xf5, 0x9f, 0x07, 0xa1, 0xa4, 0x28, 0x4b, 0x61, 0x69,
	0x0f, 0x39, 0xec, 0xf9, 0x22, 0x5b, 0xe4, 0xbe, 0x74, 0xb3, 0x61, 0xad, 0xaa, 0xc7, 0x06, 0x0f,
	0x7b, 0x7e, 0x63, 0xd9, 0x3c, 0xb3, 0x0c, 0x92, 0x53, 0xd9, 0xe2, 0xd0, 0x95, 0x95, 0xc1, 0x1e,
	0xe1, 0x4b, 0x89, 0x71, 0x88, 0xd4, 0xcf, 0x09, 0xeb, 0xdd, 0x2f, 0xf7, 0x89, 0xce, 0x23, 0xbb,
	0x87, 0xb8, 0xea, 0xb1, 0xd4, 0xc4, 0x02, 0x62, 0x67, 0xc1, 0xd0, 0xb1, 0xab, 0x27, 0x1a, 0x5a,
	0xea, 0x04, 0x43, 0x6b, 0x6c, 0xd0, 0xd2, 0xc8, 0x52, 0x27, 0xb0, 0x17, 0x77, 0x72, 0xa1, 0xf9,
	0x32, 0x5b, 0xe4, 0xc9, 0x36, 0x15, 0x76, 0x1b, 0x62, 0xde, 0x86, 0x78, 0x9d, 0xb7, 0x21, 0xcf,
	0x66, 0x93, 0x9c, 0x2e, 0x29, 0x34, 0x8f, 0xaf, 0x27, 0x9d, 0xd9, 0x24, 0xa7, 0x07, 0x14, 0x9a,
	0xc3, 0xf5, 0xa4, 0x33, 0xb3, 0x47, 0x08, 0xbf, 0xcb, 0x66, 0xc4, 0x81, 0xdf, 0x65, 0x5e, 0x9e,
	0x6c, 0x57, 0x62, 0x6a, 0x50, 0xd8, 0x72, 0xde, 0x0c, 0x94, 0x93, 0x67, 0xfd, 0x0c, 0xc9, 0x85,
	0xcc, 0x18, 0xf8, 0x66, 0xdb, 0x54, 0x5a, 0x2c, 0xe9, 0x9f, 0xad, 0x20, 0x20, 0x33, 0xb5, 0x15,
	0x4b, 0x3b, 0xec, 0xa2, 0xf7, 0xc0, 0xbe, 0x23, 0xa4, 0xcf, 0xd3, 0x7f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0x75, 0x72, 0x13, 0x37, 0x02, 0x00, 0x00,
}
