docs:
  title: Workflow

props:
  - name: register
    type: bool
    default: true
    description: Registers enabled and valid workflows and executes them when triggered

  - name: execDebug
    type: bool
    default: false
    description: Enables verbose logging for workflow execution

  - name: callStackSize
    type: int
    default: 16
    description: Defines the maximum call stack size between workflows
