// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service-corredor.proto

package corredor

import (
	context "context"
	fmt "fmt"
	proto1 "github.com/cortezaproject/corteza-server/compose/proto"
	proto2 "github.com/cortezaproject/corteza-server/system/proto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunTestRequest struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunTestRequest) Reset()         { *m = RunTestRequest{} }
func (m *RunTestRequest) String() string { return proto.CompactTextString(m) }
func (*RunTestRequest) ProtoMessage()    {}
func (*RunTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{0}
}

func (m *RunTestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTestRequest.Unmarshal(m, b)
}
func (m *RunTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTestRequest.Marshal(b, m, deterministic)
}
func (m *RunTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTestRequest.Merge(m, src)
}
func (m *RunTestRequest) XXX_Size() int {
	return xxx_messageInfo_RunTestRequest.Size(m)
}
func (m *RunTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunTestRequest proto.InternalMessageInfo

func (m *RunTestRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *RunTestRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RunNamespaceRequest struct {
	Config               map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Script               *Script           `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Namespace            *proto1.Namespace `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RunNamespaceRequest) Reset()         { *m = RunNamespaceRequest{} }
func (m *RunNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*RunNamespaceRequest) ProtoMessage()    {}
func (*RunNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{1}
}

func (m *RunNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunNamespaceRequest.Unmarshal(m, b)
}
func (m *RunNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *RunNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunNamespaceRequest.Merge(m, src)
}
func (m *RunNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_RunNamespaceRequest.Size(m)
}
func (m *RunNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunNamespaceRequest proto.InternalMessageInfo

func (m *RunNamespaceRequest) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *RunNamespaceRequest) GetScript() *Script {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *RunNamespaceRequest) GetNamespace() *proto1.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type RunModuleRequest struct {
	Config               map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Script               *Script           `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Namespace            *proto1.Namespace `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Module               *proto1.Module    `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RunModuleRequest) Reset()         { *m = RunModuleRequest{} }
func (m *RunModuleRequest) String() string { return proto.CompactTextString(m) }
func (*RunModuleRequest) ProtoMessage()    {}
func (*RunModuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{2}
}

func (m *RunModuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunModuleRequest.Unmarshal(m, b)
}
func (m *RunModuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunModuleRequest.Marshal(b, m, deterministic)
}
func (m *RunModuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunModuleRequest.Merge(m, src)
}
func (m *RunModuleRequest) XXX_Size() int {
	return xxx_messageInfo_RunModuleRequest.Size(m)
}
func (m *RunModuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunModuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunModuleRequest proto.InternalMessageInfo

func (m *RunModuleRequest) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *RunModuleRequest) GetScript() *Script {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *RunModuleRequest) GetNamespace() *proto1.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *RunModuleRequest) GetModule() *proto1.Module {
	if m != nil {
		return m.Module
	}
	return nil
}

type RunRecordRequest struct {
	Config               map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Script               *Script           `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Namespace            *proto1.Namespace `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Module               *proto1.Module    `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	Record               *proto1.Record    `protobuf:"bytes,5,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RunRecordRequest) Reset()         { *m = RunRecordRequest{} }
func (m *RunRecordRequest) String() string { return proto.CompactTextString(m) }
func (*RunRecordRequest) ProtoMessage()    {}
func (*RunRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{3}
}

func (m *RunRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRecordRequest.Unmarshal(m, b)
}
func (m *RunRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRecordRequest.Marshal(b, m, deterministic)
}
func (m *RunRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRecordRequest.Merge(m, src)
}
func (m *RunRecordRequest) XXX_Size() int {
	return xxx_messageInfo_RunRecordRequest.Size(m)
}
func (m *RunRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRecordRequest proto.InternalMessageInfo

func (m *RunRecordRequest) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *RunRecordRequest) GetScript() *Script {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *RunRecordRequest) GetNamespace() *proto1.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *RunRecordRequest) GetModule() *proto1.Module {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *RunRecordRequest) GetRecord() *proto1.Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type RunMailMessageRequest struct {
	Config               map[string]string   `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Script               *Script             `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	MailMessage          *proto2.MailMessage `protobuf:"bytes,3,opt,name=mailMessage,proto3" json:"mailMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RunMailMessageRequest) Reset()         { *m = RunMailMessageRequest{} }
func (m *RunMailMessageRequest) String() string { return proto.CompactTextString(m) }
func (*RunMailMessageRequest) ProtoMessage()    {}
func (*RunMailMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{4}
}

func (m *RunMailMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunMailMessageRequest.Unmarshal(m, b)
}
func (m *RunMailMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunMailMessageRequest.Marshal(b, m, deterministic)
}
func (m *RunMailMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunMailMessageRequest.Merge(m, src)
}
func (m *RunMailMessageRequest) XXX_Size() int {
	return xxx_messageInfo_RunMailMessageRequest.Size(m)
}
func (m *RunMailMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunMailMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunMailMessageRequest proto.InternalMessageInfo

func (m *RunMailMessageRequest) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *RunMailMessageRequest) GetScript() *Script {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *RunMailMessageRequest) GetMailMessage() *proto2.MailMessage {
	if m != nil {
		return m.MailMessage
	}
	return nil
}

type RunTestResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunTestResponse) Reset()         { *m = RunTestResponse{} }
func (m *RunTestResponse) String() string { return proto.CompactTextString(m) }
func (*RunTestResponse) ProtoMessage()    {}
func (*RunTestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{5}
}

func (m *RunTestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTestResponse.Unmarshal(m, b)
}
func (m *RunTestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTestResponse.Marshal(b, m, deterministic)
}
func (m *RunTestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTestResponse.Merge(m, src)
}
func (m *RunTestResponse) XXX_Size() int {
	return xxx_messageInfo_RunTestResponse.Size(m)
}
func (m *RunTestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunTestResponse proto.InternalMessageInfo

type RunNamespaceResponse struct {
	Namespace            *proto1.Namespace `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RunNamespaceResponse) Reset()         { *m = RunNamespaceResponse{} }
func (m *RunNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*RunNamespaceResponse) ProtoMessage()    {}
func (*RunNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{6}
}

func (m *RunNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunNamespaceResponse.Unmarshal(m, b)
}
func (m *RunNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *RunNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunNamespaceResponse.Merge(m, src)
}
func (m *RunNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_RunNamespaceResponse.Size(m)
}
func (m *RunNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunNamespaceResponse proto.InternalMessageInfo

func (m *RunNamespaceResponse) GetNamespace() *proto1.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type RunModuleResponse struct {
	Module               *proto1.Module `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RunModuleResponse) Reset()         { *m = RunModuleResponse{} }
func (m *RunModuleResponse) String() string { return proto.CompactTextString(m) }
func (*RunModuleResponse) ProtoMessage()    {}
func (*RunModuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{7}
}

func (m *RunModuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunModuleResponse.Unmarshal(m, b)
}
func (m *RunModuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunModuleResponse.Marshal(b, m, deterministic)
}
func (m *RunModuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunModuleResponse.Merge(m, src)
}
func (m *RunModuleResponse) XXX_Size() int {
	return xxx_messageInfo_RunModuleResponse.Size(m)
}
func (m *RunModuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunModuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunModuleResponse proto.InternalMessageInfo

func (m *RunModuleResponse) GetModule() *proto1.Module {
	if m != nil {
		return m.Module
	}
	return nil
}

type RunRecordResponse struct {
	Record               *proto1.Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RunRecordResponse) Reset()         { *m = RunRecordResponse{} }
func (m *RunRecordResponse) String() string { return proto.CompactTextString(m) }
func (*RunRecordResponse) ProtoMessage()    {}
func (*RunRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{8}
}

func (m *RunRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRecordResponse.Unmarshal(m, b)
}
func (m *RunRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRecordResponse.Marshal(b, m, deterministic)
}
func (m *RunRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRecordResponse.Merge(m, src)
}
func (m *RunRecordResponse) XXX_Size() int {
	return xxx_messageInfo_RunRecordResponse.Size(m)
}
func (m *RunRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunRecordResponse proto.InternalMessageInfo

func (m *RunRecordResponse) GetRecord() *proto1.Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type RunMailMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunMailMessageResponse) Reset()         { *m = RunMailMessageResponse{} }
func (m *RunMailMessageResponse) String() string { return proto.CompactTextString(m) }
func (*RunMailMessageResponse) ProtoMessage()    {}
func (*RunMailMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{9}
}

func (m *RunMailMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunMailMessageResponse.Unmarshal(m, b)
}
func (m *RunMailMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunMailMessageResponse.Marshal(b, m, deterministic)
}
func (m *RunMailMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunMailMessageResponse.Merge(m, src)
}
func (m *RunMailMessageResponse) XXX_Size() int {
	return xxx_messageInfo_RunMailMessageResponse.Size(m)
}
func (m *RunMailMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunMailMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunMailMessageResponse proto.InternalMessageInfo

type Script struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Timeout              uint32   `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Async                bool     `protobuf:"varint,4,opt,name=async,proto3" json:"async,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Script) Reset()         { *m = Script{} }
func (m *Script) String() string { return proto.CompactTextString(m) }
func (*Script) ProtoMessage()    {}
func (*Script) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06bb92bf45e37e2, []int{10}
}

func (m *Script) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Script.Unmarshal(m, b)
}
func (m *Script) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Script.Marshal(b, m, deterministic)
}
func (m *Script) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Script.Merge(m, src)
}
func (m *Script) XXX_Size() int {
	return xxx_messageInfo_Script.Size(m)
}
func (m *Script) XXX_DiscardUnknown() {
	xxx_messageInfo_Script.DiscardUnknown(m)
}

var xxx_messageInfo_Script proto.InternalMessageInfo

func (m *Script) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Script) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Script) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Script) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

func init() {
	proto.RegisterType((*RunTestRequest)(nil), "corredor.RunTestRequest")
	proto.RegisterType((*RunNamespaceRequest)(nil), "corredor.RunNamespaceRequest")
	proto.RegisterMapType((map[string]string)(nil), "corredor.RunNamespaceRequest.ConfigEntry")
	proto.RegisterType((*RunModuleRequest)(nil), "corredor.RunModuleRequest")
	proto.RegisterMapType((map[string]string)(nil), "corredor.RunModuleRequest.ConfigEntry")
	proto.RegisterType((*RunRecordRequest)(nil), "corredor.RunRecordRequest")
	proto.RegisterMapType((map[string]string)(nil), "corredor.RunRecordRequest.ConfigEntry")
	proto.RegisterType((*RunMailMessageRequest)(nil), "corredor.RunMailMessageRequest")
	proto.RegisterMapType((map[string]string)(nil), "corredor.RunMailMessageRequest.ConfigEntry")
	proto.RegisterType((*RunTestResponse)(nil), "corredor.RunTestResponse")
	proto.RegisterType((*RunNamespaceResponse)(nil), "corredor.RunNamespaceResponse")
	proto.RegisterType((*RunModuleResponse)(nil), "corredor.RunModuleResponse")
	proto.RegisterType((*RunRecordResponse)(nil), "corredor.RunRecordResponse")
	proto.RegisterType((*RunMailMessageResponse)(nil), "corredor.RunMailMessageResponse")
	proto.RegisterType((*Script)(nil), "corredor.Script")
}

func init() { proto.RegisterFile("service-corredor.proto", fileDescriptor_c06bb92bf45e37e2) }

var fileDescriptor_c06bb92bf45e37e2 = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x5f, 0x6b, 0x13, 0x41,
	0x10, 0xe7, 0x92, 0xf4, 0x6c, 0x26, 0x6a, 0xd3, 0x6d, 0x8c, 0xd7, 0x13, 0x35, 0xdc, 0x83, 0x46,
	0xc4, 0xab, 0x44, 0x04, 0xff, 0x14, 0xa1, 0x14, 0x41, 0x84, 0x8a, 0xac, 0xbe, 0xcb, 0x79, 0x59,
	0xcb, 0x61, 0x6e, 0x37, 0xee, 0xde, 0x15, 0xf2, 0x35, 0xfc, 0x3a, 0x7e, 0xa8, 0xbe, 0xfa, 0x28,
	0xb7, 0x3b, 0xf7, 0xb7, 0x49, 0xac, 0x04, 0xa4, 0x6f, 0x37, 0x33, 0xbf, 0x99, 0xdd, 0xdf, 0x6f,
	0x66, 0xe7, 0x60, 0xa8, 0x98, 0x3c, 0x8b, 0x42, 0xf6, 0x24, 0x14, 0x52, 0xb2, 0xa9, 0x90, 0xfe,
	0x5c, 0x8a, 0x44, 0x90, 0xed, 0xdc, 0x76, 0x6f, 0x87, 0x22, 0x9e, 0x0b, 0xc5, 0x0e, 0x78, 0x10,
	0x33, 0x35, 0x0f, 0x42, 0x66, 0x20, 0xee, 0x20, 0x0f, 0xc4, 0x62, 0x9a, 0xce, 0x2e, 0x78, 0x25,
	0x0b, 0x85, 0x9c, 0xa2, 0x77, 0x5f, 0x2d, 0x54, 0xc2, 0xe2, 0x83, 0x38, 0x88, 0x66, 0x5f, 0x62,
	0xa6, 0x54, 0x70, 0x8a, 0x09, 0xde, 0x21, 0xdc, 0xa4, 0x29, 0xff, 0xcc, 0x54, 0x42, 0xd9, 0x8f,
	0x94, 0xa9, 0x84, 0x0c, 0xc1, 0x56, 0x22, 0x95, 0x21, 0x73, 0xac, 0x91, 0x35, 0xee, 0x52, 0xb4,
	0x08, 0x81, 0x4e, 0x76, 0x07, 0xa7, 0xa5, 0xbd, 0xfa, 0xdb, 0x3b, 0xb7, 0x60, 0x8f, 0xa6, 0xfc,
	0x43, 0x7e, 0xb7, 0xbc, 0xc6, 0x11, 0xd8, 0xa1, 0xe0, 0xdf, 0xa2, 0x53, 0xc7, 0x1a, 0xb5, 0xc7,
	0xbd, 0xc9, 0x23, 0xbf, 0x20, 0xb8, 0x04, 0xee, 0x1f, 0x6b, 0xec, 0x5b, 0x9e, 0xc8, 0x05, 0xc5,
	0x44, 0x32, 0x06, 0x5b, 0x85, 0x32, 0x9a, 0x27, 0xfa, 0xc0, 0xde, 0xa4, 0x5f, 0x96, 0xf8, 0xa4,
	0xfd, 0x14, 0xe3, 0xe4, 0x29, 0x74, 0x0b, 0x71, 0x9c, 0xb6, 0x06, 0x13, 0x1f, 0x75, 0xf0, 0xcb,
	0xb3, 0x4a, 0x90, 0xfb, 0x12, 0x7a, 0x95, 0x23, 0x49, 0x1f, 0xda, 0xdf, 0xd9, 0x02, 0xe9, 0x66,
	0x9f, 0x64, 0x00, 0x5b, 0x67, 0xc1, 0x2c, 0xcd, 0xc9, 0x1a, 0xe3, 0x55, 0xeb, 0x85, 0xe5, 0xfd,
	0x6c, 0x41, 0x9f, 0xa6, 0xfc, 0x44, 0x8b, 0x9e, 0xd3, 0x7d, 0xd3, 0xa0, 0xfb, 0xa0, 0x46, 0xb7,
	0x86, 0xfd, 0xdf, 0x5c, 0xc9, 0x43, 0xb0, 0xcd, 0x84, 0x38, 0x1d, 0x0d, 0xdf, 0x29, 0xe0, 0x78,
	0x2f, 0x0c, 0x6f, 0x22, 0xca, 0x2f, 0x23, 0x0a, 0xd5, 0x33, 0x77, 0x39, 0x51, 0x6a, 0xd8, 0x2b,
	0x2b, 0x4a, 0x06, 0x34, 0x2f, 0xc9, 0xd9, 0x6a, 0x00, 0x91, 0x00, 0x86, 0x37, 0x51, 0xef, 0xb7,
	0x05, 0xb7, 0xb2, 0x31, 0x09, 0xa2, 0xd9, 0x89, 0x79, 0x9b, 0xb9, 0x84, 0xc7, 0x0d, 0x09, 0x1f,
	0xd7, 0xe7, 0xea, 0x42, 0xc2, 0x86, 0x3a, 0x3e, 0x87, 0x5e, 0x5c, 0xd6, 0x44, 0x25, 0xf7, 0x7c,
	0xb3, 0x3c, 0xfc, 0xea, 0x71, 0x55, 0xdc, 0x26, 0xd4, 0x77, 0x61, 0xa7, 0xd8, 0x3e, 0x6a, 0x2e,
	0xb8, 0x62, 0xde, 0x3b, 0x18, 0xd4, 0x57, 0x84, 0xf1, 0xd7, 0x9b, 0x6c, 0x5d, 0xa2, 0xc9, 0xde,
	0x21, 0xec, 0x56, 0x5e, 0x1f, 0x96, 0x29, 0x3b, 0x6f, 0xad, 0xed, 0x3c, 0x66, 0xe7, 0x63, 0x5a,
	0x66, 0xe3, 0x38, 0x58, 0x6b, 0xc7, 0xc1, 0x73, 0x60, 0xd8, 0xec, 0x10, 0xf2, 0x9b, 0x82, 0x6d,
	0x64, 0xff, 0x97, 0x45, 0x4b, 0x1c, 0xb8, 0x96, 0x44, 0x31, 0x13, 0x69, 0xa2, 0xdb, 0x72, 0x83,
	0xe6, 0x66, 0x26, 0x6e, 0xa0, 0x16, 0x3c, 0xd4, 0x93, 0xbc, 0x4d, 0x8d, 0x31, 0x39, 0x6f, 0xc1,
	0x75, 0xec, 0x6e, 0xca, 0x39, 0x93, 0xe4, 0x35, 0x74, 0x32, 0x99, 0x89, 0x53, 0x1b, 0xa1, 0xca,
	0xde, 0x77, 0xf7, 0x97, 0x44, 0x90, 0xf6, 0x7b, 0xe8, 0x16, 0x0a, 0x93, 0xbb, 0x6b, 0x77, 0xb9,
	0x7b, 0x6f, 0x55, 0x18, 0x6b, 0x1d, 0x81, 0x6d, 0x94, 0x26, 0xee, 0xea, 0x2d, 0xe9, 0xde, 0x59,
	0x1a, 0x2b, 0x4b, 0x18, 0xb9, 0x1b, 0x25, 0x6a, 0x3b, 0xa5, 0x51, 0xa2, 0xd1, 0xc8, 0x8f, 0xd0,
	0xab, 0x34, 0x87, 0xdc, 0xff, 0xcb, 0xc3, 0x72, 0x47, 0xab, 0x01, 0xa6, 0xe2, 0x57, 0x5b, 0xff,
	0x4f, 0x9f, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xef, 0xf0, 0x32, 0xb0, 0xd3, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScriptRunnerClient is the client API for ScriptRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScriptRunnerClient interface {
	Test(ctx context.Context, in *RunTestRequest, opts ...grpc.CallOption) (*RunTestResponse, error)
	Namespace(ctx context.Context, in *RunNamespaceRequest, opts ...grpc.CallOption) (*RunNamespaceResponse, error)
	Module(ctx context.Context, in *RunModuleRequest, opts ...grpc.CallOption) (*RunModuleResponse, error)
	Record(ctx context.Context, in *RunRecordRequest, opts ...grpc.CallOption) (*RunRecordResponse, error)
	MailMessage(ctx context.Context, in *RunMailMessageRequest, opts ...grpc.CallOption) (*RunMailMessageResponse, error)
}

type scriptRunnerClient struct {
	cc *grpc.ClientConn
}

func NewScriptRunnerClient(cc *grpc.ClientConn) ScriptRunnerClient {
	return &scriptRunnerClient{cc}
}

func (c *scriptRunnerClient) Test(ctx context.Context, in *RunTestRequest, opts ...grpc.CallOption) (*RunTestResponse, error) {
	out := new(RunTestResponse)
	err := c.cc.Invoke(ctx, "/corredor.ScriptRunner/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptRunnerClient) Namespace(ctx context.Context, in *RunNamespaceRequest, opts ...grpc.CallOption) (*RunNamespaceResponse, error) {
	out := new(RunNamespaceResponse)
	err := c.cc.Invoke(ctx, "/corredor.ScriptRunner/Namespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptRunnerClient) Module(ctx context.Context, in *RunModuleRequest, opts ...grpc.CallOption) (*RunModuleResponse, error) {
	out := new(RunModuleResponse)
	err := c.cc.Invoke(ctx, "/corredor.ScriptRunner/Module", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptRunnerClient) Record(ctx context.Context, in *RunRecordRequest, opts ...grpc.CallOption) (*RunRecordResponse, error) {
	out := new(RunRecordResponse)
	err := c.cc.Invoke(ctx, "/corredor.ScriptRunner/Record", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptRunnerClient) MailMessage(ctx context.Context, in *RunMailMessageRequest, opts ...grpc.CallOption) (*RunMailMessageResponse, error) {
	out := new(RunMailMessageResponse)
	err := c.cc.Invoke(ctx, "/corredor.ScriptRunner/MailMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScriptRunnerServer is the server API for ScriptRunner service.
type ScriptRunnerServer interface {
	Test(context.Context, *RunTestRequest) (*RunTestResponse, error)
	Namespace(context.Context, *RunNamespaceRequest) (*RunNamespaceResponse, error)
	Module(context.Context, *RunModuleRequest) (*RunModuleResponse, error)
	Record(context.Context, *RunRecordRequest) (*RunRecordResponse, error)
	MailMessage(context.Context, *RunMailMessageRequest) (*RunMailMessageResponse, error)
}

// UnimplementedScriptRunnerServer can be embedded to have forward compatible implementations.
type UnimplementedScriptRunnerServer struct {
}

func (*UnimplementedScriptRunnerServer) Test(ctx context.Context, req *RunTestRequest) (*RunTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (*UnimplementedScriptRunnerServer) Namespace(ctx context.Context, req *RunNamespaceRequest) (*RunNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Namespace not implemented")
}
func (*UnimplementedScriptRunnerServer) Module(ctx context.Context, req *RunModuleRequest) (*RunModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Module not implemented")
}
func (*UnimplementedScriptRunnerServer) Record(ctx context.Context, req *RunRecordRequest) (*RunRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}
func (*UnimplementedScriptRunnerServer) MailMessage(ctx context.Context, req *RunMailMessageRequest) (*RunMailMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MailMessage not implemented")
}

func RegisterScriptRunnerServer(s *grpc.Server, srv ScriptRunnerServer) {
	s.RegisterService(&_ScriptRunner_serviceDesc, srv)
}

func _ScriptRunner_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptRunnerServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/corredor.ScriptRunner/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptRunnerServer).Test(ctx, req.(*RunTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptRunner_Namespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptRunnerServer).Namespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/corredor.ScriptRunner/Namespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptRunnerServer).Namespace(ctx, req.(*RunNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptRunner_Module_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptRunnerServer).Module(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/corredor.ScriptRunner/Module",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptRunnerServer).Module(ctx, req.(*RunModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptRunner_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptRunnerServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/corredor.ScriptRunner/Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptRunnerServer).Record(ctx, req.(*RunRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptRunner_MailMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunMailMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptRunnerServer).MailMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/corredor.ScriptRunner/MailMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptRunnerServer).MailMessage(ctx, req.(*RunMailMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ScriptRunner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "corredor.ScriptRunner",
	HandlerType: (*ScriptRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _ScriptRunner_Test_Handler,
		},
		{
			MethodName: "Namespace",
			Handler:    _ScriptRunner_Namespace_Handler,
		},
		{
			MethodName: "Module",
			Handler:    _ScriptRunner_Module_Handler,
		},
		{
			MethodName: "Record",
			Handler:    _ScriptRunner_Record_Handler,
		},
		{
			MethodName: "MailMessage",
			Handler:    _ScriptRunner_MailMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service-corredor.proto",
}
