package agentic

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	autoRest "github.com/crusttech/human/server/automation/rest"
	"github.com/crusttech/human/server/automation/rest/request"
	"github.com/crusttech/human/server/pkg/mcpkit/toolkit"
	"github.com/mark3labs/mcp-go/mcp"
)

type eventTypeHandler struct {
	reg toolRegistrar
}

// The declaration for this handler is in event_type_tools.go.
func EventTypeHandler(reg toolRegistrar) *eventTypeHandler {
	h := &eventTypeHandler{reg: reg}
	h.register()
	return h
}

// lookup returns the event-type catalogue.
//
// Unlike every other tool in this package there is no service to call: the
// catalogue is generated by `make codegen` into automation/rest/eventTypes.gen.go
// as an unexported function over unexported types, and the only exported way to
// reach it is the REST controller that serves /automation/event-types. So this
// calls that controller. The alternatives were to move the generator into a
// package both layers can import — a codegen change, out of scope here — or to
// copy the list into this file, which would silently go stale the first time an
// event was added to the definitions and is the one option that must not be
// taken.
//
// The controller's payload type is unexported, so the result is re-read as
// generic JSON rather than mirrored into a local struct. That keeps the shape in
// one place too: a property added to the definitions passes through untouched.
//
// There is no authorization question to answer here, and the reason matters
// rather than the conclusion: the catalogue is a compile-time constant of
// Human's own code, identical for every caller, and says nothing about this
// instance's data or configuration. There is nothing for a service to authorize.
func (h *eventTypeHandler) lookup(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	args, err := toolkit.Args(req)
	if err != nil {
		return nil, err
	}

	payload, err := autoRest.EventTypes{}.New().List(ctx, request.NewEventTypesList())
	if err != nil {
		return nil, toolkit.Errf("event type list", err)
	}

	set, err := eventTypeSet(payload)
	if err != nil {
		return nil, err
	}

	query := strings.TrimSpace(toolkit.Str(args, "resourceType"))
	if query == "" {
		return toolkit.JSONResult(map[string]any{
			"eventTypes": set,
			"count":      len(set),
		})
	}

	matched := make([]map[string]any, 0, len(set))
	for _, def := range set {
		if matchesResourceType(def, query) {
			matched = append(matched, def)
		}
	}

	out := map[string]any{
		"eventTypes": matched,
		"count":      len(matched),
	}

	// A resourceType that matches nothing is the likely failure here — the
	// values are not guessable — so answer with the ones that do exist instead
	// of an empty result the caller has to interpret.
	if len(matched) == 0 {
		out["knownResourceTypes"] = knownResourceTypes(set)
	}

	return toolkit.JSONResult(out)
}

// eventTypeSet re-reads the controller's payload as generic JSON. See lookup for
// why it is not decoded into a typed mirror.
func eventTypeSet(payload interface{}) ([]map[string]any, error) {
	raw, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("event type list decode failed: %w", err)
	}

	var decoded struct {
		Set []map[string]any `json:"set"`
	}
	if err = json.Unmarshal(raw, &decoded); err != nil {
		return nil, fmt.Errorf("event type list decode failed: %w", err)
	}
	return decoded.Set, nil
}

// matchesResourceType matches an exact resource type, or a bare prefix against
// its sub-resources: "compose" covers "compose:record", "compose:module" and so
// on. Resource types are colon-delimited, and a caller who knows only the app
// half should not have to enumerate the rest.
func matchesResourceType(def map[string]any, query string) bool {
	rt, _ := def["resourceType"].(string)
	return strings.EqualFold(rt, query) ||
		strings.HasPrefix(strings.ToLower(rt), strings.ToLower(query)+":")
}

func knownResourceTypes(set []map[string]any) []string {
	seen := make(map[string]bool, len(set))
	for _, def := range set {
		if rt, _ := def["resourceType"].(string); rt != "" {
			seen[rt] = true
		}
	}

	out := make([]string, 0, len(seen))
	for rt := range seen {
		out = append(out, rt)
	}
	sort.Strings(out)
	return out
}
