name: 'Release'

on:
  push:
    tags:
      - '**'

env:
  BUILD_OS: linux
  BUILD_ARCH: amd64

  GO_VERSION: 1.24.1
  GOFLAGS: -mod=readonly

  NODE_VERSION: 22

  SASS_VERSION: 1.85.1

jobs:
  ########################################################################################################################
  # Server

  # server-test:
  #   name: 'Server tests'
  #   runs-on: ubuntu-22.04
  #   env:
  #     GOFLAGS: -mod=readonly
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: actions/setup-go@v6
  #       with:
  #         go-version: '${{ env.GO_VERSION }}'
  #         cache-dependency-path: server/go.sum
  #     - name: 'Copy language files'
  #       working-directory: server/pkg/locale
  #       run: make src/en
  #     - name: 'Unit'
  #       working-directory: server
  #       run: make test.unit
  #     - name: 'Store'
  #       working-directory: server
  #       run: make test.store
  #     - name: 'Integration'
  #       working-directory: server
  #       run: make test.integration

  server-web-console-build:
    name: 'Server Web Console Build'
    runs-on: ubuntu-22.04
    needs: ['lib-test']
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: 'Dependencies'
        run: pnpm install --ignore-scripts && pnpm rebuild esbuild unrs-resolver vue-demi
      - name: 'Build'
        working-directory: server/webconsole
        run: pnpm build
      - name: 'Upload webconsole dist'
        uses: actions/upload-artifact@v7
        with:
          name: webconsole-dist
          path: server/webconsole/dist
          retention-days: 1

  server-build:
    name: 'Server Build'
    runs-on: ubuntu-22.04
    needs: [server-web-console-build]
    steps:
      - run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '${{ env.GO_VERSION }}'
          cache-dependency-path: server/go.sum
      - name: 'Download webconsole dist'
        uses: actions/download-artifact@v8
        with:
          name: webconsole-dist
          path: server/webconsole/dist
      - name: 'Copy essentials'
        run: cp *.md DCO LICENSE server/
      - name: 'Copy language files'
        working-directory: server/pkg/locale
        run: make src/en
      - name: 'Build server binary'
        working-directory: server
        run: make release-clean release
      - name: 'Upload server build'
        uses: actions/upload-artifact@v7
        with:
          name: server-build
          path: server/build/pkg/human-server
          retention-days: 1

  discovery-server-build:
    name: 'Discovery Server Build'
    runs-on: ubuntu-22.04
    steps:
      - run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '${{ env.GO_VERSION }}'
          cache-dependency-path: extra/server-discovery/go.sum
      - name: 'Copy essentials'
        run: cp *.md DCO LICENSE extra/server-discovery/
      - name: 'Build discovery server binary'
        working-directory: extra/server-discovery
        run: make release-clean release BUILD_FLAVOUR=human
      - name: 'Upload discovery server build'
        uses: actions/upload-artifact@v7
        with:
          name: discovery-server-build
          path: extra/server-discovery/build/pkg/human-server
          retention-days: 1

  ########################################################################################################################
  # Libs

  lib-test:
    name: 'Library tests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: 'Install dependencies'
        run: pnpm install --ignore-scripts && pnpm rebuild esbuild unrs-resolver vue-demi
      - name: 'Test lib/js'
        working-directory: lib/js
        run: pnpm test:unit
      - name: 'Test lib/vue'
        working-directory: lib/vue
        run: pnpm test:unit

  client-web-test:
    name: 'Web client unit tests'
    runs-on: ubuntu-22.04
    needs: ['lib-test']
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: 'Install dependencies'
        run: pnpm install --ignore-scripts && pnpm rebuild esbuild unrs-resolver vue-demi
      - name: 'Test unify'
        working-directory: client/web/unify
        run: pnpm test:unit run --passWithNoTests

  ########################################################################################################################
  # Web clients

  client-web-build:
    name: 'Web client build (${{ matrix.app }})'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix: { app: [unify] }
    needs: ['client-web-test']
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: 'Dependencies'
        run: pnpm install --ignore-scripts && pnpm rebuild esbuild unrs-resolver vue-demi
      - name: 'Build'
        working-directory: client/web/${{ matrix.app }}
        run: pnpm build
      - name: 'Upload web app build'
        uses: actions/upload-artifact@v7
        with:
          name: webapp-${{ matrix.app }}
          path: client/web/${{ matrix.app }}/dist
          retention-days: 1

  ########################################################################################################################
  # Docker images

  docker-images:
    name: 'Docker image planetcrust/human'
    runs-on: ubuntu-22.04
    needs: [server-build, client-web-build]
    steps:
      - uses: actions/checkout@v6

      - name: 'Download server build'
        uses: actions/download-artifact@v8
        with:
          name: server-build
          path: .docker-build/server

      - name: 'Download webapp build'
        uses: actions/download-artifact@v8
        with:
          name: webapp-unify
          path: .docker-build/webapp-merged

      - name: 'Parse version tag'
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "DOCKER_IMAGE_TAG=${TAG}" >> $GITHUB_ENV
          if [[ "$(echo ${TAG} | grep '-')" == "" ]]; then
            echo "DOCKER_IMAGE_ALIAS=$(echo ${TAG} | cut -d '.' -f -2)" >> $GITHUB_ENV
          fi

      - name: 'Login'
        uses: docker/login-action@v4
        if: ${{ !env.ACT && env.DOCKER_IMAGE_TAG }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build'
        run: |
          docker build \
            --build-arg "VERSION=${{ env.DOCKER_IMAGE_TAG }}" \
            --build-arg "SASS_VERSION=${{ env.SASS_VERSION }}" \
            --tag planetcrust/human:${{ env.DOCKER_IMAGE_TAG }} \
            .

      - name: 'Push ${{ env.DOCKER_IMAGE_TAG }}'
        if: ${{ !env.ACT }}
        run: docker push planetcrust/human:${{ env.DOCKER_IMAGE_TAG }}

      - name: 'Push ${{ env.DOCKER_IMAGE_ALIAS }}'
        if: ${{ !env.ACT && env.DOCKER_IMAGE_ALIAS }}
        run: |
          docker tag \
            planetcrust/human:${{ env.DOCKER_IMAGE_TAG }} \
            planetcrust/human:${{ env.DOCKER_IMAGE_ALIAS }}
          docker push planetcrust/human:${{ env.DOCKER_IMAGE_ALIAS }}

  docker-image-discovery:
    name: 'Docker image planetcrust/human-server-discovery'
    runs-on: ubuntu-22.04
    needs: [discovery-server-build]
    steps:
      - uses: actions/checkout@v6

      - name: 'Download discovery server build'
        uses: actions/download-artifact@v8
        with:
          name: discovery-server-build
          path: extra/server-discovery/.docker-build/server

      - name: 'Parse version tag'
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "DOCKER_IMAGE_TAG=${TAG}" >> $GITHUB_ENV
          if [[ "$(echo ${TAG} | grep '-')" == "" ]]; then
            echo "DOCKER_IMAGE_ALIAS=$(echo ${TAG} | cut -d '.' -f -2)" >> $GITHUB_ENV
          fi

      - name: 'Login'
        uses: docker/login-action@v4
        if: ${{ !env.ACT && env.DOCKER_IMAGE_TAG }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build'
        run: |
          docker build \
            --build-arg "VERSION=${{ env.DOCKER_IMAGE_TAG }}" \
            --tag planetcrust/human-server-discovery:${{ env.DOCKER_IMAGE_TAG }} \
            extra/server-discovery

      - name: 'Push ${{ env.DOCKER_IMAGE_TAG }}'
        if: ${{ !env.ACT }}
        run: docker push planetcrust/human-server-discovery:${{ env.DOCKER_IMAGE_TAG }}

      - name: 'Push ${{ env.DOCKER_IMAGE_ALIAS }}'
        if: ${{ !env.ACT && env.DOCKER_IMAGE_ALIAS }}
        run: |
          docker tag \
            planetcrust/human-server-discovery:${{ env.DOCKER_IMAGE_TAG }} \
            planetcrust/human-server-discovery:${{ env.DOCKER_IMAGE_ALIAS }}
          docker push planetcrust/human-server-discovery:${{ env.DOCKER_IMAGE_ALIAS }}
